web3-storage/web3.storage

package-lock.json
packages/client/examples/browser/main.js
packages/client/examples/node.js/files.js
packages/client/package.json
packages/client/src/lib.js
packages/client/src/lib/interface.ts
packages/client/test/put.spec.js

Uses filelike interface in put instead of Web3File, given we do not have cid reliability on it

chore: use filelike in put

---

packages/client/package-lock.json
packages/client/package.json
packages/client/src/lib.js
packages/client/src/lib/interface.ts
packages/client/test/get.spec.js

- Update client.get to use https://github.com/web3-storage/ipfs-car/pull/46
- uses a blockstore during unpack so should be able to deal with cars larger than mem now.
- ipfs-car adopts the ReadableStream vs AsyncIterator shim which is nice
- Adds `clean` target called before `build` to ensure we're fresh.

feat: feat: client.get uses unpackStream

---

.github/workflows/api.yml
packages/api/wrangler.toml

- update wrangler.toml with staging env
- update github action to publish staging api on merge to main
and out-of-band we have:
- web3.storage site created on Cloudflare
- nameservers updated to point web3.storage at Cloudflare
- DNSSEC enabled on web3.storage
- Scoped api token for editing workers on web3.storage added as `CF_API_TOKEN`

chore: staging api config

---

package-lock.json
packages/api/webpack.config.js

I was getting this error trying to run `npm run build` in the api package:
```bash
npm run build
> web3.storage-api@0.0.0 build
> webpack
1 asset
201 modules
ERROR in ./src/index.js 52:13-20
Module not found: Error: Can't resolve 'process/browser' in '/Users/yusef/work/repos/web3.storage/packages/api/src'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
webpack 5.42.0 compiled with 1 error in 466 ms
```
Using node v16.4.0, npm 7.18.1 on an M1 mac.
Changing the webpack config entry …

fix: webpack build process

---

.github/workflows/release.yml

Create release PRs for the client and the api with CHANGELOGs from semantic commit messages. 
When merging a release PR:
-  for the client it will bump the the package.version, tag the repo, and publish the module to npm. 
-  for the api it will bump the the package.version, tag the repo, and publish the prod worker to Cloudflare 
Pulled over from @hugomrdias's lovely work in https://github.com/ipfs-shipyard/nft.storage/blob/98d83ea00a26363632ddaa33ab632831218f5a1e/.github/workflows/release.yml
Documented and trimmed down to just publish the client to npm, or the worker to prod. We're not yet generating client jsdocs or publishing the website.
TODO:

chore: add release-please CI worklow

---

packages/api/src/index.js
packages/api/src/user.js
packages/api/test/mocks/db/post_graphql.js
packages/api/test/user.spec.js
packages/db/fauna/resources/Function/deleteAuthToken.js
packages/db/fauna/schema.graphql

* Adds the endpoint `DELETE /user/tokens/:id`
* Adds a GQL function `deleteAuthToken(user: ID!, authToken: ID!)` which sets the `deleted` flag on the token provided the token owner is the passed `user`.
* Fixes for bad codings

feat: user token delete

---

.github/workflows/api.yml

we no longer rely on wranglers built in webpack, so we must npm install before deploying

chore: install before staging deploy

---

.github/workflows/api.yml
.github/workflows/release.yml

see: https://github.com/cloudflare/wrangler-action/issues/59
see: https://github.com/web3-storage/wrangler-action/pull/1

chore: use node@16 & npm@7 when building workers

---

packages/api/wrangler.toml

enforce https on api route and dont deploy to workers.dev domain
see: https://developers.cloudflare.com/workers/platform/routes#route-patterns-may-optionally-begin-with-http-or-https

chore: force wrangler to deploy to custom domain

---

packages/api/wrangler.toml

This should, finally, allow us to deploy to the staging and prod domains from CI.

chore: add cloudflare zone_id for staging and prod

---

.github/workflows/release.yml

too many hyphens spoils the yaml

chore: fix release yaml

---

packages/api/wrangler.toml

wrangler.toml environments do not inherit vars
see: https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys
Cluster is not renamed yet, so is filecoin.storage for now
see: https://github.com/protocol/bifrost-infra/issues/1319

chore: set CLUSTER_API_URL for staging & prod

---

package-lock.json
packages/api/package.json
packages/api/src/index.js

This PR updates the `playwright-test` dependency.
The new version ensures the service worker is registered after the tests bundle is requested. This prevents the service worker responding to a fetch request for the bundle that contains the tests.
The worker no longer has to distinguish between requests for the worker and requests for other resources as everything should be for the worker (as it would be in production).

chore: update playwright

---

packages/api/src/car.js
packages/api/src/env.js
packages/db/fauna/resources/Function/findUploads.js
packages/db/fauna/resources/Function/importCar.js
packages/db/fauna/resources/Index/uploadByUserAndContent.js
packages/db/fauna/resources/Index/uploadByUserSortByCreatedDesc.js
packages/db/fauna/schema.graphql
packages/website/pages/new-file.js

* Creates an index of `Upload`s by `user` and `content`
* Fixes `importCar` to check for an existing `Upload` from the user for the given CID and returns that if found
* This effectively allows split CAR uploads by not creating a new `Upload` object for every chunk of CAR that is uploaded

fix: split CAR uploads

---

packages/db/README.md
packages/db/package.json

The FQL refernces Collections that the GQL import step creates, so do `import:gql` first
Fixes #49

fix: import gql schema before fql indexes

---

package-lock.json
packages/w3/bin.js
packages/w3/index.js
packages/w3/package.json
packages/w3/utils/glob-source.js

adds a `--put` command to `w3`.
```console
$ w3 --put pics --token <your token here... this is temporary>
+ /pics/dr-is-tired.jpg
+ /pics/not-distributed.jpg
+ /pics/youareanonsense.jpg
⁂ https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
```
glob-source is ported from ipfs-utils to be esm and make files in the shape that client.put expects them.

feat: w3 --put /path/to/files

---

package-lock.json
package.json
packages/w3/bin.js
packages/w3/index.js
packages/w3/package.json
packages/w3/utils/glob-source.js

- `w3 get <cid>` fetch files by cid and verify them
- `w3 put <path>` upload files to web3.storage
- switches `meow` for `sade` for the subcommand support.
**upload in progress**
```console
$ w3 put ~/Desktop/output/week-in-web3-2021-07-02.mov
⠧ Storing 48%
```
**success ✨**
```console
$ w3 put ~/Desktop/output/week-in-web3-2021-07-02.mov
⁂ Stored 1 file
⁂ https://dweb.link/ipfs/bafybeigzwx5ychvapyslpmgy7hwdwh6nabyapxkjmpmtwwqevv4zpwfauy
```

feat: subcommands for w3

---

packages/client/src/lib.js
packages/client/src/lib/interface.ts
packages/client/test/get.spec.js

Previously calling `res.files()` on the response from `client.get` would return an array of Files with a `.cid` property that was a CID instance. This PR makes it a string, to be consistent with the our other usages of CID which are all strings. If folks need to upgrade their string CIDs to instances of CID then the `CID.parse(str)` method is the one to use.
A breaking change for the client API! 

fix!: cid prop on web3file is a string

---

.github/workflows/db.yml

- add db workflow that runs the fauna resource import script when a change is merged to main
- `STAGING_FAUNA_KEY` is added to repo.

chore: deploy staging db from ci

---

packages/db/fauna/resources/Function/addBatchEntries.js
packages/db/fauna/resources/Function/createBatch.js
packages/db/fauna/resources/Index/batchEntryByBatchAndContent.js
packages/db/fauna/schema.graphql

The max payload for Fauna is around 10MB, but even then the query backing this operation can only deal with around 10,000 entries before it throws "An internal server error occurred. Please contact Fauna support.".
This PR splits the `createBatch` call into two: 1) `createBatch` and 2) `addEntries`, so that a batch can be created and then entries can be added to the batch. The `createBatch` method no longer takes a list of entries.
You use it like this now:
```gql
mutation {
createBatch(data: { batchCid: "bafybatch", pieceCid: "baga" }) {
_id
}
}
mutation {
addBatchEntries(
batchCid: "bafybatch",
entries: [{ cid: "QmFile", dataModelSelector: "Links/0/Hash" }]
) {
_id
}
}
```

refactor: allow chunked adding of batch entries

---

packages/api/src/cors.js
packages/api/src/index.js
packages/api/test/cors.spec.js

Making debugging failures less awkward.
fixes #73

fix: set cors headers on errors

---

packages/api/README.md
packages/api/src/status.js
packages/api/test/fixtures/find-content-by-cid-no-batch.json
packages/api/test/fixtures/find-content-by-cid-no-deal.json
packages/api/test/fixtures/find-content-by-cid-unknown.json
packages/api/test/fixtures/find-content-by-cid.json
packages/api/test/fixtures/status.json
packages/api/test/mocks/db/post_graphql.js
packages/api/test/status.spec.js

- add `created` denoting when we first saw this content
- add `pins.updated` for when the pin status last changed
- add `deals.created` and `deals.updated` to the filecoin deal status
- updated tests and docs
- fix 404 logic
fixes https://github.com/web3-storage/web3.storage/issues/78#issuecomment-880065131
**Example status response**
```json
{
"cid": "testcid",
"created": "2021-07-14T19:27:14.934572Z",
"dagSize": 101,
"pins": [{
"peerId": "12D3KooWR1Js",
"peerName": "who?",
"region": "where?",
"status": "Pinned",
"created": "2021-07-14T19:27:14.934572Z",
}],
"deals": [{
"dealId": 12345,
"miner": "f99",
"status": "Active",
"pieceCid": "baga",
"dataCid": "bafy",
"dataModelSelector": "Links/0/Links",
"activation": "<iso timestamp>",
"created": "2021-07-14T19:27:14.934572Z",
"updated": …
```

feat: add timestamps to /status/:cid response

---

package-lock.json
packages/w3/package.json

- using the previous major causes an explosion
- also update the package-lock.json with all the missing changes from previous PRs

chore: w3 needs to use the same ipfs-car version

---

package-lock.json
packages/w3/bin.js
packages/w3/index.js
packages/w3/package.json

`w3 token` will prompt you to paste in your api key
```console
$ w3 token
✔ Paste your API token for api.web3.storage · eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJk...etc
⁂ API token saved
```
and as with all other commands, you can pass in a custom --api
```console
w3 token --api https://api-staging.web3.storage
✔ Paste your API token for api-staging.web3.storage · eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJk...etc
⁂ API token saved
```
and now w3 will save that token and api (via [`conf`](https://github.com/sindresorhus/conf) to an appropriate config dir per you OS. AND! it warns you if you are using an API other than PROD! 🎉
```console
w3 put ~/Pictures/pmf.jpg
⁂ using api-staging.web3.storage
⁂ Stored 1 file
⁂ https://dweb.link/ipfs/bafybeicwehe4cx74f5gf2duol7g5kgqmkh4z7ivnqi …
```

feat: `w3 token` and `w3 status` commands

---

packages/api/src/car.js
packages/cron/src/jobs/pins.js
packages/db/fauna/schema.graphql

Turns out `Int` is an 32bit integer not 64bit https://docs.fauna.com/fauna/current/api/graphql/#supported-scalar-types
This PR switches to using `Long`.

fix: switch dagSize type to Long

---

packages/api/scripts/add-mock-deals.js

This adds a script for creating some mock deals in your local development database for content you've already added.
Make sure your database is up to date first by running `npm run import` in the `packages/db` directory.
It's safe to run multiple times to get more deals for your data.
Sample script output:
After the script has run you should be able to see deals for your CIDs e.g.

feat: mock deals script

---

packages/api/scripts/add-mock-deals.js
packages/api/src/status.js
packages/api/test/fixtures/find-content-by-cid.json
packages/api/test/fixtures/status.json
packages/api/test/status.spec.js
packages/client/src/lib/interface.ts
packages/client/test/fixtures/status.json
packages/db/fauna/resources/Function/createOrUpdateDeal.js
packages/db/fauna/schema.graphql
packages/website/content/about.md

As per https://www.notion.so/protocollabs/FIP-Operational-renaming-proposal-for-miner-ecosystem-d1e286a2a4254510b98681ceb9c8ed85 this PR renames "miner" to "storageProvider".
This also adds an optional `dagSize: Long` to `AggregateEntryInput` which we can use to populate `dagSize` on `Content` for really big DAGs.

refactor: rename miner to storage provider

---

package-lock.json
packages/api/src/car.js
packages/api/src/upload.js
packages/api/test/mocks/db/post_graphql.js
packages/db/fauna/resources/Function/createUpload.js
packages/db/fauna/schema.graphql

This PR adds a `type` property to `Upload` allowing us to track and produce metrics on the type of upload data received. It also renames `importCar` method to `createUpload` that takes a required `type` param.
Note: if you have existing uploads you'll need to add a `type: 'Car'` parameter to them in leu of a migration!
resolves #115

feat!: add upload type property

---

packages/api/wrangler.toml

web3.storage.ipfscluster.io is the thing

chore: update the cluster domain

---

package-lock.json
packages/w3/package.json

✨🎷🐩
sets the access flag in the package.json so I can trigger another release-please PR for the `w3` package.

fix: set npm publish access to public

---

packages/client/package.json

trims out about 0.8MB and 46 files from the published build
**before**
```
npm notice package size:  898.9 kB
npm notice unpacked size: 2.0 MB
npm notice total files:   70
```
**after**
```
npm notice package size:  284.4 kB
npm notice unpacked size: 1.2 MB
npm notice total files:   24
```

fix: remove dev files from published client

---

.github/workflows/release.yml

Update website prod deploy to use web3.storage.

chore: release website via web3.storage

---

packages/client/src/lib.js
packages/client/test/get.spec.js

- remove the spcial case to return undefined on a 404. We get from the gateway currently so any valid CID would either be returned succesfully or fail with a non 404 error code, so this 404 would not occur in the wild
- the plan is to have the api redirect to get from a dedicated gateway when we host the CID, and redirect to the public gateway where the user tries to get a CID we dont recognise.

fix: throw on 404 from /get

---

packages/api/test/user.spec.js

Removes `console.log` in tests

chore: remove test log

---

package-lock.json
packages/api/package.json
packages/client/package.json
packages/client/src/lib.js
packages/w3/package.json

This makes `ipfs-car` packing with a `maxChunkSize` of  1048576  and a `maxChildrenPerNode` 1024.
We will keep using `sha256` hasher instead of [@multiformats/blake2](https://www.npmjs.com/package/@multiformats/blake2) given it is way slower (a minimal set of tests showed ~6x slower)
Needs:
resolves #173

fix: make unixfs importer on ipfs-car use same defaults as lotus

---

packages/website/pages/index.js

Fixes two docs links. Should link to the homepage, anchor id link `#quickstart` instead of `/quickstart`.

fix: fix two docs links to quickstart

---

packages/website/pages/files.js

Now the date always show Date + Time depending on the user's locale
American: 
Portuguese:
Closes https://github.com/web3-storage/web3.storage/issues/164

Chore: files page date format

---

packages/w3/bin.js
packages/w3/index.js
packages/w3/test/bin.spec.js

- Auto resolving of the package.json does not work for `sade` or `conf` in ESM world, so we do it manually.
```console
$ w3 --version
w3, 1.1.0
```
fixes #167
see: https://github.com/sindresorhus/conf/issues/150

fix: get version of w3 cmd from package.json

---

.github/workflows/cron-pinata.yml
.github/workflows/cron-pins.yml

Start the crons for prod to set pin status, dag size, and backup to pinata

chore: enable cron jobs for prod

---

.github/workflows/cron-pinata.yml
.github/workflows/cron-pins.yml

chore: fix fauna_key used in cron

---

packages/website/pages/index.js
packages/website/styles/global.css

Constrain the code-sample max width, to match the grid above it.
**after**

chore: max width for code sample box

---

packages/website/pages/files.js

- Fixes pagination for the files page (only shows next button if there's actually more items to show)
I feel like I cheated the system, but I'm fetching 25 items and only showing 24 in the UI, and only if we have 25+ items left, it shows the "next"
Related to https://github.com/web3-storage/web3.storage/issues/178

chore: fix pagination in the files page

---

packages/website/pages/files.js

Displays something in the table when there is no deal information to see yet.

feat: show enqueuing uploads

---

packages/api/src/car.js
packages/website/pages/files.js

After initial add, Cluster will usually report "Unpinned" when queried immediately. This PR polls cluster for status after adding until a preferable pin status is obtained from at least one of the nodes i.e. PinQueued, Pinning or Pinned.
The UI now shows the best pin status we have across all pins.

fix: query cluster until we get a preferable pin status

---

packages/website/pages/files.js

Closes https://github.com/web3-storage/web3.storage/issues/211
Looks like this now:

chore: fix files page being full width when empty

---

packages/api/src/cors.js
packages/api/src/metrics.js

In production, GET /metrics was failing due to immutable headers. Let's just add them when creating the response

fix: metrics immutable headers

---

.github/workflows/api.yml
.github/workflows/client.yml
.github/workflows/cron-pinata.yml
.github/workflows/cron-pins.yml
.github/workflows/db.yml
.github/workflows/lint.yml
.github/workflows/w3.yml
.github/workflows/website.yml
package-lock.json

`npm run build --workspace=packages/api` fails with node 16.6, so we should stick to node 16.5 for now.

chore: change ci node version to 16.5

---

packages/api/src/user.js
packages/website/components/types.d.ts
packages/website/content/file-a-request.js
packages/website/lib/api.js
packages/website/pages/account.js
packages/website/pages/tokens.js
packages/website/styles/global.css

- Makes the account page a beautiful pixel-perfect page by matching the figma specs
- Account page now fetches storage capacity and shows it accordingly (with a sexy animation)
https://user-images.githubusercontent.com/24696635/127491981-a16b1b7e-8439-4a68-86b6-5bfc00969989.mov
- Fixes token cards with huge titles

fix: account page ui makeover

---

packages/api/src/car.js
packages/api/src/constants.js
packages/api/test/car.spec.js
packages/api/test/mocks/db/post_graphql.js

Adds a restriction to CAR uploads to ensure we don't store a block that cannot be transferred over the IPFS network.

feat: restrict block size

---

.github/workflows/api.yml
.github/workflows/client.yml
.github/workflows/cron-pinata.yml
.github/workflows/cron-pins.yml
.github/workflows/db.yml
.github/workflows/lint.yml
.github/workflows/w3.yml
.github/workflows/website.yml
packages/api/package.json

since node 16.6 webpack-cli fails to load esm config unless WEBPACK_CLI_FORCE_LOAD_ESM_CONFIG=true
see: https://github.com/nodejs/node/pull/39175
see: https://github.com/webpack/webpack-cli/blob/a660ffcbeb2807bce1554f787297e697464abd59/packages/webpack-cli/lib/webpack-cli.js#L50-L51

fix: force webpack to load ESM config

---

packages/db/fauna/resources/Function/createUpload.js

If an existing upload object is found we currently return it, without updating the user's `usedStorage` with the `chunkSize`.
It's more likely that this is a chunked upload and we need to add on the chunk size to the user's `usedStorage`.

fix: update usedStorage for chunked uploads

---

packages/api/src/car.js
packages/api/src/utils/pin.js

This PR moves the pin status polling into `waitUntil` and increases the periodi between polls and the max amount of time to spend polling.
This will hopefully result in faster uploads and quicker pin status updates.

fix: move pin ok status polling into waitUntil

---

packages/api/src/car.js
packages/api/src/upload.js
packages/db/fauna/resources/Function/createUpload.js
packages/db/fauna/resources/Function/incrementUserUsedStorage.js
packages/db/fauna/schema.graphql

This PR alters the `createUpload` UDF to not update the user's `usedStorage` and changes the API to call a separate small UDF called `incrementUserUsedStorage` as a background task.
Having a separate function just for updating `usedStorage` will hopefully decrease lock contention and running in `waitUntil` ensures the overall request does not fail even if we're not able to do the accounting.

fix: increment user used storage in waitUntil

---

packages/api/src/car.js
packages/api/test/car.spec.js

Adds a check to ensure the received CAR has at least 1 block in it.

fix: check for empty CAR

---

packages/db/fauna/resources/Function/findPinsByStatus.js
packages/db/fauna/resources/Index/pinByStatusSortByCreatedDesc.js

This means we process the head of the queue first.

fix: find pins by status sort by created DESC

---

packages/api/README.md

This PR adds the API docs by the [authmoji PR](https://github.com/web3-storage/web3.storage/pull/237).
Given the admin API routes are scoped into the website, I did not document their parameters/response type to avoid creating noise in what is important for the users. Let me know if you would like them in.
Resolves #96

chore: update api docs

---

package-lock.json
packages/cron/package.json
packages/cron/src/jobs/pins.js
packages/db/fauna/resources/Function/updatePins.js
packages/db/fauna/schema.graphql

This reduces the time taken to update pin statuses for 1,000 pins from ~15m to ~5s.
Status requests from cluster are super quick, but DB requests are slower. This switches to using a bulk update UDF, called once per 1,000 pins.
resolves https://github.com/web3-storage/web3.storage/issues/273

perf: faster pin status sync

---

packages/w3/bin.js
packages/w3/index.js

- Pass `--no-retry` to `w3 put` to have it fail on the first error. Useful for debugging.
- If you want to get really specific you can pass `--retry <number>` to assert how many times you want to try.
```console
$ w3 put pinpie.jpg --no-retry
⁂ using api-staging.web3.storage
⁂ maxRetries: 0
...
```
```console
$ w3 put -h
Description
Upload a file or directory to web3.storage
Usage
$ w3 put <path> [options]
Options
--no-wrap     Dont wrap input files with a directory.
--no-retry    Dont try the upload again if it errors.
-h, --help    Displays this message
```

feat: `w3 put --no-retry`

---

packages/api/src/car.js
packages/api/test/car.spec.js

If a CAR file is sent to us that has a single block (the root block) and that block has links, then it is an invalid partial DAG.

fix: disallow CAR of single block with links

---

packages/db/fauna/resources/Function/deleteUploadByUserAndContent.js
packages/db/fauna/resources/Function/findContentByCreated.js
packages/db/fauna/schema.graphql

* `deleteUploadByUserAndContent` for cleaning up when we receive partial DAG and the full `dagSize` is never calculated. The existing UDF `deleteUserUpload` cannot be used for this purpose as it requires a `dagSize` so that it can do data usage accounting.
* `findContentByCreated` is for metrics generation on content.

feat: additional UDFs for admin purposes

---

packages/cron/src/jobs/metrics.js
packages/db/fauna/resources/Function/createOrUpdateMetric.js
packages/db/fauna/schema.graphql

Allow specify the time the metric was updated. The "to date" is chosen when the cron starts and when it finishes it saves a metric with an updated date that is much further in the future than the chosen "to date". This PR changes the mutation and UDF to accept an `updated` date so next time the cron runs, it's "from date" is the previous runs "to date" and we don't miss any data in the counts.

fix: incremental metrics

---

packages/website/components/layout.js
packages/website/components/navbar.js
packages/website/components/types.d.ts
packages/website/lib/magic.js
packages/website/lib/user.js
packages/website/pages/about.js
packages/website/pages/account.js
packages/website/pages/callback.js
packages/website/pages/files.js
packages/website/pages/index.js
packages/website/pages/new-token.js
packages/website/pages/tokens.js
packages/website/pages/upload.js

This PR removes the call to `magic.user.getMetadata()`. We do no use the result of this call anywhere at the moment and it has been observed to add 0.5s onto the time it takes the site to determine if the user is logged in.

fix: remove unused user metadata request

---

packages/client/README.md

This PR edits packages/client/README.md to explain that you need two terminal windows open in order to test the client code against the mock API.

Describe how to run mock API

---

packages/website/pages/account.js

Removes the second spinner for the account page - they're using the same variable so it's redundant to have both
Closes #337

fix: remove second spinner for the account page

---

.github/workflows/cron-pins-failures.yml
packages/cron/package.json
packages/cron/src/bin/pins.js
packages/cron/src/jobs/pins.js

Adds a cron job to run once a day and check in with cluster on pins that have the status PinError.
If a pin gets the status `PinError` then we currently do not check again on it. Howveer Cluster does not stop trying to retrieve the CID and in the case of a failed upload the user may successfully re-upload it.
I ran this locally and it updated the status of 4,424 pins that were in the `PinError` state.

feat: cron to update status for PinError pins

---

package-lock.json
packages/client/package.json
packages/client/src/lib.js
packages/client/src/lib/interface.ts
packages/client/test/put.spec.js

This PR adds an optional parameter to `putCar` called `decoders`. It's an array of IPLD `BlockDecoder`.
It's needed when the DAG in the CAR file was not encoded using the default encoders `dag-pb`, `dag-cbor` and `raw`.

feat: support any IPLD decoder

---

packages/db/fauna/resources/Function/deletePinSyncRequests.js
packages/db/fauna/resources/Function/deleteWithHistory.js

Stops history accumulating on `PinSyncRequest` collection.
`deleteWithHistory` provided by Fauna support.
Currently deployed to prod.

fix: pin sync request history

---

packages/cron/src/jobs/pinata.js
packages/db/fauna/resources/Function/deletePinRequests.js
packages/db/fauna/schema.graphql

Suggested by the fauna team, a similar fix to https://github.com/web3-storage/web3.storage/pull/385. The code was calling the auto-generated `deletePinRequest` function, which does not delete the document snapshots, and leads to a build of of data that slows down queries until they fail to complete within the time budget.

fix: delete fauna history when deleting PinRequest

---

packages/website/content/about.md

This adds a paragraph to the "Storage term" section of the about page to clarify that deleting files from the web UI won't necessarily remove them from IPFS. Closes #372 
I copied the warning from the storage how-to referenced in the issue and tweaked it a little bit to refer to "users" instead of "you".

chore: warn about deletion behavior on about page

---

.github/workflows/release.yml

The `website-prod` branch is configured on Cloudflare pages to be our production branch. The CI job updates that branch after a website release PR is merged.
This set up makes it so cloudflares view of what is our production deployment matches our view of it. Keeping that in sync means we can use the built in Rollback a deployment feature on Pages, and is less confusing for the bleary eyed fire-fighter.
All other branches get preview builds on Cloudflare. We can't have that be more selective, so all PRs regardless of what code they touch will get a Cloudflare Pages status. To be less noisy I have disabled the "add a comment to the PR" option. The check is still available in the list at the bottom of the PR which should be suffcient.
All of the `add-to-web3` plubming is left in place, so …

chore: deploy website to cloudflare pages on release

---

.github/workflows/release.yml
.github/workflows/website.yml

Ensure that the add-to-web3 github action uses the prod api.

chore: use prod api when adding to web3

---

.github/workflows/cron-test.yml

The pit canary. A minimally viable smoke test for uploading to web3.storage that can run frequently and alert us if it dies.
In it's current form it will test both staging and production with small files and random files sligtly larger than the local add threshold. I'd like to replace the random files with wikipedia pages or similar, but this will do for now.
it'll let us know when the latest published `w3` command, using the latest published `web3.storage` client is working, which is nice.
WIP on https://github.com/web3-storage/web3.storage/issues/421

chore: test upload via w3 on cron

---

.github/workflows/api.yml
.github/workflows/client.yml
.github/workflows/cron-test.yml
.github/workflows/db.yml
.github/workflows/w3.yml

- Simplify and fix cron end-to-end test. It just tests against production now.
- Add an e2e upload test as the last step in CI for each of the relevant components [api,client,db,w3]

chore: fix upload test cron

---

packages/website/components/footer.js

This is the thing now https://status.web3.storage/

chore: update statuspage link to https://status.web3.storage/

---

packages/website/components/button.js
packages/website/components/layout.js
packages/website/components/navbar.js
packages/website/pages/account.js
packages/website/pages/files.js

This makes the header less janky by always rendering the links to the Files and Account pages, which now redirect to `/login/` instead of `/` if you're not logged in.
It also renders a login button with a loading spinner while it's checking the auth state, instead of rendering nothing and popping in the button once the state resolves.
@olizilla you mentioned doing this yesterday, and I figured it would be a good stop-gap until we can make the actual auth flow faster.

Always show header links & login/out button

---

.github/workflows/cron-test.yml

this will allow us to alert on failed tests from prometheus and track upload durations.
The metric:
```
web3storage_upload_duration_seconds{endpoint="/car",size="3MiB",cmd="w3"} 4.59
```
tells us how long in seconds it took to upload a 3MiB file to the /car endpoint via the w3 command.
it is imagined that we could also test via curl `cmd=curl` and with other sizes `size=100MiB` (careful with the carinality there tho) or other endpoints `endpoint=/files`.

chore: track upload test results in prometheus

---

package-lock.json
packages/api/package.json
packages/api/src/car.js
packages/api/src/upload.js
packages/api/webpack.config.js

- Have the API pack uploaded files into a CAR, to make the two paths more similar and ideally simplify the upload to S3 path.
-  We need to test this out on staging to see how it impacts the total file size folks can upload, as now we have to have the upload and the CAR in memory at the same time.
- Simplify dagSize calcualtion. If it's a dag-pb root, then just derive the cumulative size of the dag in the same way that ipfs does from the sum of the link sizes and the node size. if it's not dag-pb, just use the sum of the block sizes in the CAR. 
- This means we dont have to walk the entire DAG and we can get a dagSize figure for dags that are split across mutiple CARs (assuming they stick to the treewalk strategy from carbites, and each contain the root block).
License: (Apache-2.0 AND …

chore: unify /upload and /car uploads

---

.github/workflows/release.yml

We want to see all the interesting changes in the changelog, even chores and refactors.
see: https://github.com/marketplace/actions/release-please-action#overriding-the-changelog-sections

chore: add chores and refactors to the changelog

---

packages/api/src/upload.js

Use the same maxChunkSize & maxChildrenPerNode values as the js-client
Follow on from #480 

chore: bring upload car settings inline with client

---

packages/api/src/upload.js
packages/db/fauna/schema.graphql

The PR to unify /car and /upload https://github.com/web3-storage/web3.storage/pull/480 was merged and changed the Upload type provided to the Database from `Directory` / `Blob` to `Upload`, keeping `Car` to when using the /car endpoint.
This is causing problems in production because `enum type 'UploadType'. Known values are: Car, Blob, Multipart` per https://github.com/web3-storage/web3.storage/blob/website-v1.4.0/packages/db/fauna/schema.graphql#L262-L274
This PR reverts this back to the original behaviour. However, given everything is going to be stored as a Car, maybe the best solution is to either drop this property, or really change its type to `Upload` in the Database schema.

fix: upload type in upload should be blob or directory

---

packages/db/fauna/resources/Function/createUpload.js
packages/db/fauna/resources/Index/backupByUploadAndUrl.js

https://github.com/web3-storage/web3.storage/pull/417 was merged but follow up chunk backup URLs were not properly stored. Only the first one was stored, instead of each single one. This was because of the short circuit where we just return an upload if there is one. In this situation, we need to update the Backup collection
Considering comment https://github.com/web3-storage/web3.storage/pull/417#discussion_r707451630 , an index was also added to verify if the backup url for the given upload already exists. Considering that we will not create the upload entry and we will not create the content entry, this should not result in much more computing power to finish the mutation.

fix: chunked backup creation

---

package-lock.json
packages/api/package.json
packages/api/src/env.js
packages/api/webpack.config.js

Match up the release name reported during deploy with the release name reported at run time. This PR lines things up so releases appear in sentry like `web3-api@<semver>` which it automagically parses nicely. We currently we deploy as `<sort git sha>` but we report as `api-<semver>`.
see: https://sentry.io/organizations/protocol-labs-it/releases/web3-api%403.5.1/?project=5866408
- `SENTRY_RELEASE` env var is set during the build, and used for both creating the release at build time and on error reports so they get matched up and our sourcemap is used to unravel the stacktrace.
- Rename the bundle to be `worker.js` as that is what cloudflare renames (!?) it to on deploy, and errors are reported as coming from `worker.js` in production, so that has to match or else the source map is not …

fix: source mapping and commit info in sentry

---

packages/db/postgres/client.js
packages/db/postgres/functions.sql
packages/db/postgres/tables.sql
packages/db/test/upload.spec.js

In Fauna, when a user A deleted a given upload, if then the user uploads exactly the same file, a new Upload document was created, instead of flipping `deleted`. This means we will have same URLs. With Postgres we will not have this situation anymore. However, for DB migration let's allow replicated URLs to ingest data. Then we can remove replicated ones. Pin Sync requests currently also have multiple

fix: backup should not have unique url

---

packages/db/fauna/client.js

Fauna Graphql query can only receive what `UpdatePinInput` type contains

fix: fauna pins cron

---

packages/db/postgres/functions.sql
packages/db/test/upload.spec.js

#580 had removed this for data ingestion, but forgot it on https://github.com/web3-storage/web3.storage/pull/597
Already updated function in production schema

fix: add on conflict clause to create backup

---

packages/db/db-client-types.ts
packages/db/postgres/client.js
packages/db/postgres/functions.sql

Postgres REST returns a number from a Bigserial, which for really large Bigserials gets a different number. This PR casts all the IDs into text

fix: bigserial id cast to string

---

.github/workflows/api.yml
packages/api/test/mocks/pgrest/post_rpc#create_key.js

We changed the create key to be a rpc call instead of a post. But mocks in the API were not updated and tests are now failing...
I also made the API CI Job to track changes in the DB module to avoid future regressions

fix: create key mock

---

packages/cron/src/jobs/pins.js
packages/pinpin/src/index.js

When calling delete  on https://github.com/web3-storage/web3.storage/blob/main/packages/db/postgres/client.js#L533 to delete pinRequests + PinSyncRequests on cron jobs the requests could fail given the Postgrest URL was too big. After some tests, 400 Pins seemed the most reasonable number to use.

fix: max pin requests per run in cron and pinpin

---

packages/api/test/mocks/pgrest/post_rpc#pin_from_status_total.js
packages/db/postgres/functions.sql
packages/db/postgres/metrics.js
packages/db/postgres/tables.sql

Improves metrics related queries to get the API endpoint working:
- supabase count was not properly doing the count, but getting all the rows instead, which was too slow.
- added an unique index to cid including `dag_size` to speed up `pin_dag_size_total` rpc function.
All thanks to @ribasushi 
New function already created into production DB

fix: performance metrics queries

---

packages/api/test/mocks/pgrest/post_rpc#pin_from_status_total.js
packages/db/postgres/metrics.js

We kept count as returned from supabase client, but when getting it as an rpc call it returns it as data. Fix from bug introduced on https://github.com/web3-storage/web3.storage/pull/625

fix: pin status metrics returns data object

---

packages/db/postgres/tables.sql

This PR adds missing indexes for all foreign keys. They were already added in the DB

chore: add missing indexes for fk

---

packages/db/index.js

The status API was working fine to get the deals, but the same was not true for the list of uploads. When the query was simplified, the `content_cid` was removed from the query and we can rely on the content relation to ask the deals for the correct cid

fix: list uploads fetch deals for correct cid

---

packages/api/README.md
packages/api/src/user.js

Also fixes the API docs. The docs.web3.storage mentions the url search parameter to be `limit`, which was also the root reason for this problem. The option was already `size` previously when using fauna https://github.com/web3-storage/web3.storage/blob/api-v3.0.0/packages/api/src/user.js#L259 in the older version.
Needs:
Closes #598

fix: support upload list page size up to 1000

---

packages/db/postgres/tables.sql

Running `node scripts/cli.js db-sql` without `--reset` is currently failing because we're trying to recreate types that already exist, we should check first.
I'm not sure if there are better implementation to check if a type already exists 🤔

fix: create new types only if they do not exist

---

packages/db/postgres/functions.sql

Porting fauna counterpart with status was missed in migration: https://github.com/web3-storage/web3.storage/blob/db-v2.6.4/packages/db/fauna/resources/Function/sumPinDagSize.js#L31
This was already added to prod DB

fix: pin dag size metric should filter by pinned status

---

packages/api/src/car.js
packages/api/src/env.js

Import just the bits we need because this s3 client library is a monster and imports about 200 modules. Fixes the following error (for now):
```
Error: Something went wrong with the request to Cloudflare...
Script startup timed out.
[API code: 10021]
```
refs #79

fix: script startup timeout

---

packages/api/test/mocks/pgrest/post_rpc#find_deals_by_content_cids.js
packages/db/index.js
packages/db/utils.js

Per https://github.com/web3-storage/web3.storage/pull/677#pullrequestreview-813653126 filters out deals with other status.
Also normalizes activation and termination per:
- https://github.com/web3-storage/web3.storage/blob/cd04716844a646d986f53aeae7c73840a008aad3/packages/api/src/status.js#L40

fix: deal normalize should filter out unexpected deal status

---

packages/api/test/mocks/pgrest/post_rpc#find_deals_by_content_cids.js
packages/db/utils.js

In the DB these are lowercase, so ALL deals were being filtered out. They are expected to be uppercase-first in API responses though.

fix: deal status filtering

---

packages/client/src/lib.js

Fixes #581 
This pr reworks the problematic error message to not use the coalesce operator to resolve webpack4 issues.
In the future might look at the current rollup config and transpile to es5 or another valid syntax and export for older build setups. This however is a quick and easy solution for this specific build issue.
I verified this by creating a webpack 4 config and found the issue and resolved locally. This isn't the most foolproof way, but whenever I fixed it this way, create-react-app using webpack 4 successfully compiled, and angular 13 does not have this issue, it used webpack 5 now.

fix: Issue 581 Webpack 4 build error

---

packages/api/src/env.js
packages/client/src/lib.js

So we can see in error reports if the JS client is being used.
Also alters the `X-Client` value and adds the suffix `/js` as we also have a golang client.
see also https://github.com/web3-storage/go-w3s-client/pull/7

feat: enable sentry to record X-Client request header

---

packages/api/src/user.js
packages/api/test/user.spec.js
packages/client/test/mocks/api/get_user#uploads.js

If this value is not encoded, the "+" is interpreted as a space, and it produces an invalid date string, causing the service to respond with "invalid before date".
```js
new URL('https://api.web3.storage/user/uploads?size=25&before=2021-11-25T22:57:31.887+00:00').searchParams.get('before')
"2021-11-25T22:57:31.887 00:00"
new Date('2021-11-25T22:57:31.887 00:00')
Invalid Date
```
The issue is not seen in tests because we happen to not use `+00:00` (we use `Z` instead) but this is a valid date string currently returned by our service:

fix: encode created date in Link header

---

packages/db/postgres/config.sql
packages/db/scripts/cmds/db-sql.js
packages/infra/heroku/init.sh

We changed the max parallel workers per gather to 4 in production when we moved to Postgres. Let's keep track of it in the infra setup scripts

fix: postgres set max parallel workers per gather to 4

---

packages/client/src/lib.js

Prefixing with slash will chop off any existing pathname from the base URL. Without the slash it is appended onto the end:
```js
> new URL('/car', 'https://api.web3.storage/_backdoor/').toString()
'https://api.web3.storage/car'
> new URL('car', 'https://api.web3.storage/_backdoor/').toString()
'https://api.web3.storage/_backdoor/car'
// ...the usual case of domain only or domain with trailing slash still works:
> new URL('car', 'https://api.web3.storage').toString()
'https://api.web3.storage/car'
> new URL('car', 'https://api.web3.storage/').toString()
'https://api.web3.storage/car
```

fix: endpoint URL construction

---

packages/client/rollup.esm.config.js

Without this option, we get `import require$$0 from"buffer";` (+more) in the bundle, which cannot be resolved when used in the browser (what it is for).

fix: do not prefer node.js builtins

---

packages/db/index.js

Remaining bits of removing the materialized view. Makes the status/list uploads calls tolerant to failures from cargo
Needs:

fix: tolerant of failure for deals

---

packages/db/postgres/functions.sql
packages/db/postgres/tables.sql

This PR relaxes the uniqueness constraint on the `backup` table to include the `upload_id`.
The constraint was previously on the `url` field so that multiple uploads of the same CAR file by the same user don't result in multiple rows in the table.
With the upcoming historical data backups we'll be saving _complete_ CAR files to `<bucket_host>/complete/<CID>.car`. We want to create backup records that point to that URL but the CID may have been uploaded by multiple users.
Relaxing the constraint to include the `upload_id` ensures multiple uploads can point to the same _complete_ backup URL whilst retaining the original intention of uniqueness on `url`.
I will run the following SQL to migrate staging and production:
```sql
CREATE UNIQUE INDEX CONCURRENTLY backup_upload_id_url_key ON backup …
```

fix: backup unique constraint

---

packages/client/package.json

Bump the versions of `parse-link-header` dependencies to fix the below build (e.g. `yarn build`) issue in react-scripts v5.
```
Module not found: Error: Can't resolve 'querystring' in '/web3-storage/node_modules/parse-link-header'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
- install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "querystring": false }
```
**NOTE**: If the user bumped the react-scripts from v4 to v5, then they can just use …

Fix the react-scripts-v5 compatible issue.

---

packages/api/wrangler.toml

Using heroku endpoint instead of DNS resolution from CF gives us ~100ms improvements in response times.
Thanks @hugomrdias ❤️

fix: db endpoint to use heroku

---

PEERS

A list of known IPFS peers that are hosting content uploaded to NFT.Storage.
YOU DO NOT NEED THIS LIST. All peers that provide content on IPFS are
discoverable via the DHT. IPFS transfers content P2P from multiple sources
including other peers that recently acquired the content.
Note: this list may be incorrect, may change, or become out of date at any
time without notice.
resolves #548

feat: add list of known peers hosting content for web3.storage

---

.github/workflows/cron-dagcargo-sizes.yml
.github/workflows/cron-pins.yml
packages/api/src/car.js
packages/cron/README.md
packages/cron/package.json
packages/cron/src/bin/dagcargo-sizes.js
packages/cron/src/jobs/dagcargo.js
packages/cron/src/lib/utils.js

This PR fixes wrong computation of dag size with non pb roots.
It adds a cron job to check them in dagcargo in the same way nft.storage operates.
Please note that some older Fauna related code was removed within the cron package. Namely, the ENV vars to use different DBs and its client function.
Closes #759

fix: dag size for big dags with non pb root

---

package-lock.json
packages/api/src/car.js

When updating cluster client in https://github.com/web3-storage/web3.storage/pull/855 I missed the breaking change from https://github.com/nftstorage/ipfs-cluster/pull/14

fix: api cluster add car explicitly

---

.github/workflows/api.yml
.github/workflows/release.yml
packages/api/webpack.config.js

We can use one project for all environments, given sentry can already know the environment running and we can also filter within it.
Needs:
After merge:
Closes #760

fix: use single sentry project

---

packages/website/assets/illustrations/spring.js
packages/website/components/account/filesManager/filesManager.tsx
packages/website/components/breadcrumbs/breadcrumbs.js
packages/website/components/card/card.js
packages/website/components/footer/footer.js
packages/website/components/imageblock/imageblock.js
packages/website/components/navigation/navigation.js
packages/website/components/tokens/tokensManager/tokensManager.js
packages/website/modules/zero/components/filterable/filterable.js
packages/website/next-env.d.ts
packages/website/next.config.js
packages/website/pages/404.js
packages/website/pages/_app.tsx

_(This PR relates to the new site in development in `feat/new-brand-frontend`)_
Adding `next` and `next/core-web-vitals` to the `.eslintrc.js` should identify all the issues that will make the site compatible with `next build` and `next export`. 
Some of those issues are resolved in this PR, as are a lot of the errors that were being thrown from `tsc`. 
`eslint` however (`eslint '{pages,components,hooks,content,store}/**/*.{js,ts,tsx}'` still throws a number of errors that I wanted you to take a look at (3 errors right now that cause linting to exit). These are the same errors that appear when running `npx next build`, so this is probably what's preventing the static site output as well.

fix: next and ts linting cleanup

---

packages/db/postgres/tables.sql

This PR updates pin composite index for performance reasons on dag cargo queries, as well as adds an index for `inserted_at` which is used as part of the update dag size job in https://github.com/web3-storage/web3.storage/blob/main/packages/cron/src/jobs/dagcargo.js#L3-L31

perf: update pin composite index and adds inserted at index to content

---

packages/db/postgres/tables.sql

In NFT.Storage pin requests are added to the upload table with type "Remote". In dagcargo, PSA pin requests from Web3.Storage are combined with uploads (as they are in NFT.Storage) and are artificially given a type "Remote". Hence specifically adding a "Remote" type here would be problematic.

docs: add note about reserved Remote upload type

---

packages/api/scripts/cli.js

Fixes:
```
Error: Command failed: /github/workspace/node_modules/@sentry/cli/sentry-cli releases new @web3-storage/api@5.0.8-dev+c1f7a1b
error: Invalid value for '<VERSION>': Invalid release version. Slashes and certain whitespace characters are not permitte
```

fix: sentry version cannot contain slash

---

packages/api/package.json

After merging [PR](https://github.com/web3-storage/web3.storage/pull/902/files) trying to run the local API I got 
```
> npm start
....
Error: Something went wrong with the request to Cloudflare...
Uncaught SyntaxError: Unexpected token ':'
at line 1
[API code: 10021]
```
The problem got resolved by updating the main api entry to `index.mjs` (as pointed out to the [doc])(https://developers.cloudflare.com/workers/cli-wrangler/configuration#modules)
Interestingly after checkouting the main branch now it works without this, but I guess that's because of caching

fix: update package.json main entry

---

package-lock.json
packages/api/README.md
packages/api/package.json
packages/api/src/env.js
packages/api/src/index.js
packages/api/src/name.js
packages/api/test/name.spec.js
packages/api/test/scripts/helpers.js
packages/api/wrangler.toml

This PR adds support for websockets to w3name. Establish a websocket connection to `wss://api.web3.storage/name/:key/watch` and receive JSON encoded messages like: `{ key: string, value: string, record: string }` when updates to the key are published.
supersedes https://github.com/web3-storage/web3.storage/pull/653
Related to https://github.com/web3-storage/web3.storage/issues/659

feat: websockets support for w3name

---

packages/client/package.json

This adds the `./dist/bundle.esm.min.js` file to the `exports` field in `package.json`, as suggested by @jilt in [this comment](https://github.com/web3-storage/web3.storage/issues/549#issuecomment-1015236158) on #549. closes #549.
Should hopefully fix issues with compiling the pre-bundled ESM build for production webpack builds.
@jilt, would you mind testing this PR to see if it works with your setup? Thanks!

fix: add pre-bundled ESM build to package exports

---

packages/api/src/user.js
packages/db/index.js
packages/db/test/upload.spec.js

When the delete route is called with an upload that does not exist (it can already be deleted), the DB client should not throw and be the API who creates the error. DB should return null as it couldn't delete any upload and return an ID

fix: db client do not throw error when no upload found

---

packages/db/postgres/tables.sql

Remove temporary table used for DB migration from Fauna to Postgres

chore: remove migration tracking table

---

packages/website/components/codepreview/codepreview.js
packages/website/components/codepreview/codepreview.scss

Visual effects and animations added in this PR:
1. Height transition on the code preview window when switching tabs
2. Hover effect on inactive tabs ("Store" and "Retrieve")
3. The last line of code in the selected tab appears like it's being typed out when it enters the viewport and when switching tabs
4.  A 'copy to clipboard' button appears when hovering over the code block
Copy to clipboard functionality has also been added

feat Code preview animations

---

packages/db/postgres/tables.sql

* pinning allowlist and user account storage limits can be managed by this single table without the need for one-off tables e.g. pinning_authorization.
* this allows the admin.storage site to easily manage tags.
nft pr [here](https://github.com/nftstorage/nft.storage/pull/1243)

Adding user_tag table to facilitate user restricted application features.

---

packages/api/src/car.js
packages/api/src/errors.js
packages/api/test/car.spec.js

This PR fixes invalid CAR errors being 500 Internal server error, which will cause alerts to be triggered to sentry for user input.

fix: invalid CAR errors

---

packages/api/.env.local.tpl
packages/api/README.md
packages/api/package.json

- add a .env.local file to configure miniflare for local dev.
- update README with a much simpler "Getting Started" path.
Having just waded through the old getting started process again, this is *so much better* and I love it.

chore: use miniflare for local dev

---

packages/website/components/account/storageManager/storageManager.scss
packages/website/components/account/storageManager/storageManager.tsx
packages/website/components/card/card-tier.js
packages/website/components/card/card.js
packages/website/components/card/card.scss
packages/website/components/codepreview/codepreview.js
packages/website/lib/utils.js
packages/website/next-env.d.ts

Added animations to storage progress bars in tiers cards and the storage manager in the app ui. When cards first enter the viewport the progress bar now animates from 0 to its intended width. I added the function for checking if an element is in the viewport to `lib/utils` for use in the future.

style: data progress bar animation

---

package-lock.json
packages/api/src/utils/pin.js
packages/cron/src/jobs/pins.js
packages/db/db-client-types.ts
packages/db/index.d.ts
packages/db/index.js
packages/db/test/pin-sync-request.spec.js

We were looping a list of pins and using `upsertPin` to change the status to 'Pinned'. Instead we should use `upsertPins` to batch update all of them in one request.

fix: use upsertpins

---

.github/workflows/api.yml
packages/api/scripts/cli.js
packages/api/src/env.js
packages/api/test/scripts/worker-globals.js
packages/api/test/version.spec.js

tweak the esbuild define config to set the git info in the api build.
The `define` api only replaces the exact token, where it finds it seperated by whitespace, with the exact value provided. So the key `VERSION` was not matching on `env.VERSION`, so our envAll function now sets these values on the env for us by pulling them from magic globals that esbuild will set.
I removed the `define` config for ENV as i'm pretty sure that is set at runtime by cloudflare/miniflare and we shouldn't be attempting to burn it into the worker bundle, but would like someone to sanity check me there.
```console
❯ curl "https://api.web3.storage/version"
{"mode":"rw"}
❯ curl "http://127.0.0.1:8787/version"
{"version":"web3-api@5.1.4-dev+9068490","commit":"9068490aaa4dbe037e8e6aa9eaad706a46f11aed","branch":"main …
```

fix: version endpoint info

---

packages/website/.babelrc
packages/website/next.config.js

Getting this on cloudflare:
```
16:03:34.483 | info  - Creating an optimized production build...
-- | --
16:03:34.974 | info  - Attempted to load @next/swc-linux-x64-gnu, but it was not installed
16:03:34.976 | info  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
16:03:34.985 | info  - Attempted to load @next/swc-linux-x64-musl, but it was not installed
16:03:34.986 | error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```
Disabling for now as per: https://nextjs.org/docs/messages/failed-loading-swc

fix: disable swc minify

---

packages/api/.env.local.tpl
packages/api/src/car.js
packages/api/src/constants.js
packages/api/src/env.js
packages/api/test/cors.spec.js
packages/api/test/scripts/worker-globals.js
packages/api/wrangler.toml
packages/tools/docker/cluster/docker-compose.yml

[Issue](https://github.com/web3-storage/web3.storage/issues/923) 
Moving GATEWAY to environment to allow to point to dockerized ipfs gateway in development.

Move GATEWAY to env and expose ipfs gateway

---

packages/api/package.json
packages/api/scripts/cli.js
packages/api/src/env.js
packages/api/wrangler.toml

Screenshot shows we now get **stacktraces!** _and_ **Request info** like the url and the user agent!!11!
fixes: https://github.com/web3-storage/web3.storage/issues/983
previous: https://github.com/web3-storage/web3.storage/pull/505

chore: sentry sourcemaps for worker.mjs

---

package-lock.json
packages/client/package.json

Updates deps, specially noted `@web-std/blob@3.0.4` has an important fix for Node.js usage of Blob and `files-from-path@0.2.4` has a new feature requested from community.

fix: client update deps

---

package-lock.json
packages/api/package.json
packages/api/src/car.js
packages/api/src/env.js

add `x-amz-checksum-sha256` header on s3 object put requests.
This is nice as we reuse our existing sha256 hash of the car as an integrity check. AWS will calculate the sha256 of the body it receives and send us a 400 BadDigest error if they dont match, to avoid storing CARs that had bits flipped in transit.
It was necessary to update to the latest version of the aws-sdk as support for sha256 integrity checking was not supported in the older one.
Some debug logging is left in for the s3 client in dev mode, as it was an absolute pain to figure out what it was doing otherwise.
see: #1036
see: https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#AmazonS3-PutObject-request-header-ChecksumSHA256

fix: verify s3 backup integrity on upload

---

packages/api/src/utils/pin.js
packages/cron/src/jobs/pins.js
packages/cron/test/mocks/cluster/get_pins#@cid.js

When the DB was updated to use the IPFS node peer ID instead of the Cluster node peer ID the pin status syncing stopped working.

fix: pin status syncing

---

packages/api/src/utils/pin.js

While we don't fix https://github.com/web3-storage/web3.storage/issues/1089 this was added to production

fix: tmp workaround for lack of ipfs peer id on status response

---

packages/api/src/utils/pin.js
packages/api/test/car.spec.js
packages/api/test/fixtures/init-data.sql
packages/cron/src/jobs/pins.js
packages/cron/test/mocks/cluster/get_pins#@cid.js
packages/db/db-client-types.ts
packages/db/index.js
packages/db/postgres/functions.sql
packages/db/postgres/migrations/003-add-ipfs-peer-ids.sql
packages/db/postgres/pg-rest-api-types.d.ts
packages/db/postgres/reset.sql
packages/db/postgres/tables.sql
packages/db/test/backup.spec.js
packages/db/test/pin-request.spec.js
packages/db/test/pin-sync-request.spec.js
packages/db/test/pin.spec.js
packages/db/test/pinning.spec.js
packages/db/test/status.spec.js
packages/db/test/upload.spec.js
packages/db/test/utils.js
packages/db/utils.js

Reverts https://github.com/web3-storage/web3.storage/pull/966 and instead stores the IPFS peer ID in the `pin_location` table.

fix: store IPFS peer IDs

---

packages/db/postgres/functions.sql
packages/db/test/pin.spec.js

For every upload we lock every `pin_location` record to update it with values that never change. This PR changes that behaviour to only insert into the table if the row does not exist.
It results in two `SELECT`s for the same row on the `pin_location` table but the idea is that this will be better than locking the records.
fixes https://github.com/web3-storage/web3.storage/issues/1099 🤞

fix: pin_location lock contention

---

packages/api/src/utils/pin.js
packages/api/src/utils/psa.js
packages/db/README.md
packages/db/package.json
packages/db/postgres/migrations/004-add-UnexpectedlyUnpinned-status.sql
packages/db/postgres/pg-rest-api-types.d.ts
packages/db/postgres/tables.sql
packages/db/scripts/cmds/pg-rest-api-types.js

Pins cron is currently failing with:
```
Error: unknown tracker status: unexpectedly_unpinned
at toPinStatusEnum (file:///home/runner/work/web3.storage/web3.storage/packages/api/src/utils/pin.js:52:11)
at file:///home/runner/work/web3.storage/web3.storage/packages/cron/src/jobs/pins.js:67:20
at Array.map (<anonymous>)
at updatePinStatuses (file:///home/runner/work/web3.storage/web3.storage/packages/cron/src/jobs/pins.js:52:49)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async main (file:///home/runner/work/web3.storage/web3.storage/packages/cron/src/bin/pins.js:16:3)
```
https://github.com/web3-storage/web3.storage/runs/5509298651?check_suite_focus=true
...this is because we do not model this new status in our API code or in our DB schema yet.
resolves …

fix: add missing status UnexpectedlyUnpinned

---

packages/api/src/utils/psa.js
packages/api/test/fixtures/init-data.sql
packages/api/test/pin.spec.js

Resolves #1102
While I'm pretty confident the fix in this PR should solve the bug reported in #1102, reviewing this made me suspect the logic for filtering PSA pin requests is buggy.
Currently, [here](https://github.com/web3-storage/web3.storage/blob/main/packages/api/src/utils/psa.js#L14)'s the logic we use to convert from Cluster to Psa status does not match the way we filter by those statuses.
We're currently using `query.in('content.pins.status', opts.statuses)` to filter psa requests, but given we different nodes might report different statuses, the same requests might be filtered in different statuses not exclusively.
Here's a description of the bug:
if for a specific CID, 1 node reports `Pinned` and one `Pinning`, the same request would show up in 
`/?status=pinned` and …

fix: add missing statuses

---

packages/website/components/messagebanner/messagebanner.js

This fix changes the conditional logic on the calculation of the message banner height. The height was prevented from being re-calculated after maintenance messages fetched from the status page api came in some time after component load. Now the container recalculates its height on receiving a new maintenance message.

fix: Message banner obscuring nav

---

package-lock.json
packages/website/package.json

Upgrading this dependency fixes the npm install issue but it's a major version bump and I'm not sure how to verify if it still works. The site builds and runs just fine.
```
npm ERR! code 1
npm ERR! path /Users/alan/Code/web3-storage/web3.storage/node_modules/optipng-bin
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! node:internal/child_process:413
npm ERR!     throw errnoException(err, 'spawn');
npm ERR!     ^
npm ERR! 
npm ERR! Error: spawn Unknown system error -86
npm ERR!     at ChildProcess.spawn (node:internal/child_process:413:11)
npm ERR!     at spawn (node:child_process:700:9)
npm ERR!     at /Users/alan/Code/web3-storage/web3.storage/node_modules/bin-check/index.js:22:12
npm ERR!     at /Users/alan/Code/web3-storage/web3.storage/node_modules/executabl …
```

fix: website dependency install issue on m1

---

packages/website/content/pages/index.json

```console
$ npm install Web3.Storage
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/Web3.Storage - Not found
npm ERR! 404 
npm ERR! 404  'Web3.Storage@*' is not in this registry.
npm ERR! 404 This package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan/.npm/_logs/2022-03-18T12_00_04_881Z-debug-0.log
```

fix: npm package name

---

packages/api/scripts/add-mock-deals.js
packages/api/test/fixtures/init-data.sql
packages/api/test/hooks.js
packages/api/test/scripts/helpers.js
packages/db/index.js
packages/db/package.json
packages/db/postgres/docker/docker-compose.yml
packages/db/postgres/truncate.sql
packages/db/scripts/cli.js
packages/db/scripts/cmds/db-sql.js

Resolves #642 
In this PR
- flush DB at every test
- expose DB utils so that we can share factories to populate DB from client packages 
- fixed a nasty bug where multiple results were returned from .single because of inconsistent versions of fetch. (one used in the APIs and the one used when calling a factory from tests). TL;DR accept header was sent twice and the second instance was ignored by PostgRest.
- moved randomCid and, refactored to use `Math.random`

chore: improv api testing

---

packages/client/src/lib.js

Replaces the import candidate `content` property with a getter function that allows the stream to be created (and file descriptor opened) only when it is accessed.
The issue is that when there are many thousands of files in a directory, we'll attempt to open that many file descriptors eagerly, which can cause `EMFILE` errors on some systems.
refs https://github.com/nftstorage/nft.storage/issues/1672
refs https://github.com/nftstorage/nft.storage/pull/1693

fix: create stream when needed

---

packages/docs/code-snippets/how-to/index.js

This PR changes docs on how to handle response from web3.storage client.get. It was using a property `path` from Web3File type which does [not](https://github.com/web3-storage/web3.storage/blob/web3.storage-v4.0.0/packages/client/src/lib/interface.ts#L158-L163) exist. 
We create the File with its path as name per https://github.com/web3-storage/web3.storage/blob/web3.storage-v4.0.0/packages/client/src/lib.js#L416-L441 and we should recommend users to rely on name property to have this type as close as possible to [Web File](https://developer.mozilla.org/en-US/docs/Web/API/File)
Closes https://github.com/web3-storage/docs/issues/226

docs: fix client retrieval example web3 file property

---

packages/docs/docs/examples/getting-started.md

This example does not support a CLI parameter with file path and should only receive token.
Closes https://github.com/web3-storage/docs/issues/228

docs: remove file parameter in node example

---

packages/docs/docs/how-tos/pinning-services-api.md

The latest version of the docs includes a page in the how-to's that was written more recently than the new docs design. This PR moves that page to `web3.storage/docs`.
Closes #1160 and #1154.

fix: restore pinning services api docs page

---

.github/workflows/website.yml

The dnslink for the website should be updated when we do a prod release of the website. This PR should bring that back.

chore: bring back dnslink publishing for website

---

packages/docs/docs/how-tos/troubleshooting.md

feat: docs troubleshooting

---

packages/db/postgres/migrations/006-update-admin_search-view-to-return-users-with-no-tokens.sql
packages/db/postgres/tables.sql

The previous join was based on the assumption that admins only wanted to see users with tokens. That is no longer valid. This new join returns users from the user table whether or not they have tokens. This is the same PR that was merged into nft.storage a few weeks ago: https://github.com/nftstorage/nft.storage/pull/1668

fixes #1133: Allow admins to search for users with no tokens

---

package-lock.json
packages/api/package.json
packages/api/test/car.spec.js
packages/api/wrangler.toml
packages/tools/docker/cluster/docker-compose.yml

The IPFS Cluster v1 release has much improved perf, and some breaking API changes.
In this PR we upgrade the ipfs-cluster client and local test environment to work with the v1 cluster API.
- Our integration tests have been updated to use the v1 cluster and now pass with this changeset. 
- This PR is also tested locally by pointing a dev api at the `nft.storage.ipfscluster.io` cluster which is now used for QA and is running ipfs-cluster@v1.0.0-rc.4
- The staging deployment should be tested when this PR is merged to main.
The **staging API cluster credentials must be updated** on Cloudflare after this PR is merged to main.
To deploy to production we need to:
- Put the API into READ-ONLY (check, do we read from cluster in read-only? if so do we hit any api that has changed?
- Deploy …

feat: api support for ipfs-cluster@1.0

---

packages/website/components/account/filesManager/fileRowItem.scss

Fixing issue where checkmark in safari is always checked.
Safari does not support negative stroke-dashoffset so I've adjusted it to use positive value. However, this affects the transition animation. So in order to "fix" it, I've just made safari to animate opacity instead of "drawing tick".

fix: safari checkmark is always checked

---

package-lock.json
packages/cron/package.json

Adopt the new ipfs-cluster client to be ready for the ipfs cluster v1 roll out.
Should be merged to main **after** the production cluster is upgraded to v1
see: https://github.com/web3-storage/web3.storage/issues/1184
see: https://github.com/web3-storage/web3.storage/pull/1227

chore: cron pin update for cluster@1.0

---

.github/workflows/website.yml

_dnslink is not being updated for web3.storage as https://github.com/web3-storage/web3.storage/runs/5987111338?check_suite_focus=true workflow tasks `Add to web3.storage` and `Deploy https://web3.storage` have not been running.
They were re-enabled on https://github.com/web3-storage/web3.storage/pull/1200 but it looks that there is a typo and the condition is falsy (previous workflow steps have `steps.tag-release.outputs.releases_created`

fix: website deploy workflow release tag condition

---

packages/api/src/upload.js

`HTTPError.throw(error.message, 400)` was not properly receiving status code, leading to non handling of https://sentry.io/organizations/protocol-labs-it/issues/3185331407/?project=5864302

fix: return 400 on malformed form data

---

packages/website/components/account/filesManager/fileRowItem.js
packages/website/pages/api/user/uploads/index.js

- CIDs that appear in the files table are now linked to a gateway URL
- All links open in a new tab
Closes #1164 and #1175

feat: CID links in files table

---

packages/db/db-client-types.ts
packages/db/index.js
packages/db/postgres/pg-rest-api-types.d.ts
packages/db/test/upload.spec.js
packages/db/utils.js

This PR updates DB listUploads to return sourceCid instead of the normalized cid (from content table) in the normalization. This way, it is propagated to the website, client and w3 and only we handle normalized cid internally.
Closes https://github.com/web3-storage/web3.storage/issues/1202

fix: list uploads should return source cid

---

packages/api/src/env.js

https://github.com/web3-storage/web3.storage/pull/1272 did not trigger release PR for API because it is not in the path of packages/api per https://github.com/web3-storage/web3.storage/runs/6174595070?check_suite_focus=true

fix: trigger api release with db change

---

packages/api/src/constants.js

go-ipfs's chunker produces blocks containing 1MiB of data, however the protobuf wrapping each block results in ~0.001MiB of overhead. This means that when uploading CAR files containing blocks that go-ipfs produces, sometimes there are well-formed blocks that exceed the current limit. I am proposing bumping the max block size accepted by web3.storage to the limit imposed by ipfs bitswap, which seems like it's more in line with the reasoning behind imposing a block size limit.
The 2MiB value selected is proposed by @Jorropo in the ipfs Discord, who claims that it's a part of the bitswap spec. This value is also mentioned in ipfs/go-ipfs#3104

fix: Bump MAX_BLOCK_SIZE to 2MiB limit imposed by bitswap

---

packages/api/test/hooks.js

trying to stop the api tests from failing like https://github.com/web3-storage/web3.storage/runs/6217415452?check_suite_focus=true

chore: increase api test setup timeout

---

packages/docs/sidebars.js

Adds a link to the pinning service docs to the sidebar and fixes the page layout.
see: https://web3.storage/docs/how-tos/pinning-services-api/
preview

fix: add pinning service docs to sidebar

---

packages/website/components/card/card.js
packages/website/components/card/card.scss
packages/website/content/pages/index.json
packages/website/pages/index.scss

A fix to update the index page testimonial cards with the correct behaviour outlined below:
If a card has a link in its description:
- Clicking anywhere on the card takes the user to that link (in a new tab)
- Hovering over the card shows the current glow effect
- The text that's linked should still be underscored (currently shown with a bottom border)
If the card does not have a link in its description:
- Hovering on the card does not produce the hover effect
- The card is not clickable

fix: testimonial cards link behavior

---

.github/workflows/api.yml
.github/workflows/client.yml
.github/workflows/w3.yml
.github/workflows/website.yml

Configure release-please to write `chore` commits to the CHANGELOG as an "Other Changes" section.
This allows us to quickly verify all the code changes going into a release before deploying
See: https://github.com/google-github-actions/release-please-action#overriding-the-changelog-sections

chore: add chores to CHANGELOG

---

.github/workflows/cron-storage-limits.yaml

Fixes #1193.
This adds the GitHub workflow configuration for running the cron job to send email notifications about users approaching or over their storage limits.
Notes:
* It's currently only configured for staging, because we want to test it there before adding it to production.
* I've configured it so that it can be run manually like [this](https://docs.github.com/en/github-ae@latest/actions/managing-workflow-runs/manually-running-a-workflow) (as well as running on its schedule).
* It requires the MailChimp API key to be added to the `MAILCHIMP_API_KEY` secret. I don't think I've got access to the right stuff in GitHub to be able to do this.

feat: add github workflow cron job for storage limit email alerts

---

packages/website/components/account/ctaCard/CTACard.scss
packages/website/components/account/filesManager/fileRowItem.scss
packages/website/components/account/filesManager/filesManager.scss
packages/website/components/account/storageManager/storageManager.scss
packages/website/components/tokens/tokenCreator/tokenCreator.scss
packages/website/components/tokens/tokensManager/tokenRowItem.scss
packages/website/components/tokens/tokensManager/tokensManager.scss
packages/website/pages/account/index.js
packages/website/pages/account/index.scss
packages/website/pages/login/index.scss
packages/website/pages/tokens/index.js
packages/website/pages/tokens/index.scss

This is a new PR based on the changes requested in [this PR](https://github.com/web3-storage/web3.storage/pull/1291). It was easier to scale all rem values in the app UI based off of current values in `main` rather than the increased values in `style-scale-up-app-ui`.
Now all rem values in the app UI have been increased by a factor of 1.25 and the container width has been increased from 61.25rem to 64rem. All app pages have been tested at all breakpoints without issues. No changes were made to the file uploader modal. When scaling the modal up by 1.25 the contents tended to overflow the page introducing a scroll bar and it seemed to just look better with the original sizing. But if we want to scale this as well it can easily be done.

style: Rescale app ui

---

packages/api/src/index.js

Otherwise, for OPTIONS requests, the `corsOptions` function returns a response, meaning that `envAll` is never called, and so when the router tries to call `env.log.end()` we get an error.
This is fixing something which I broke with #1270.
The problem is that in packages/api/src/index.js at the top we now do this:
```js
const router = Router()
router.options('*', corsOptions)
router.all('*', envAll)
```
and then further down we do this:
```js
await env.log.end(response)
return response
```
But the `corsOptions` function is not a middleware - it actually returns a response. So for an options request, the `envAll` never gets called, and so `env.log` is `undefined` and the `env.log.end()` causes an error.
The solution is simply to put the `envAll` call first. This fixes the problem and also …

fix: swap the order of `corsOptions` and `envAll` to avoid error

---

packages/website/components/account/filesManager/fileRowItem.js

The mistakenly generated link on the CID header item in the app UI file manager has been removed and replaced with regular text:

fix: Remove mistakenly generated link in file manager header

---

packages/api/src/auth.js
packages/api/src/errors.js
packages/db/index.js

When an API key is blocked in admin.storage, it sets deleted_at to the current time, and then sets the last auth_key_history item to have status 'Blocked.'  This PR just updates the code to look at the status so it can send a unique error to the client when an API key is deleted via a block.  Refers to #1382 in nft.storage.

feat: respond with unique error message when blocked API key is used

---

packages/website/components/contexts/uploadsContext.js

Changing the order of execution of the `fetchDate` state change and `isFetchingUploads` state change in the uploads context fixed the problem of requesting the uploads list twice.

fix: Set fetch date before changing isFetching state

---

packages/db/postgres/functions.sql
packages/db/postgres/migrations/011-user_used_storage-update-and-email-history-table.sql

Fix type/functions problems with migrations that appeared because of changes to the same code that happened in master and account notification PR.

fix: inaccurate used_stotrage migrations

---

packages/cron/src/jobs/storage.js
packages/cron/src/lib/email/service.js
packages/cron/test/email.spec.js
packages/db/db-client-types.ts
packages/db/test/email.spec.js

We shouldn't be converting bigints to numbers to avoid integer overflow.

chore: do not convert bigint to number

---

packages/cron/src/jobs/storage.js
packages/cron/test/storage.spec.js
packages/db/postgres/migrations/010-add-admin-user.sql

As specified in #990, these notification emails should go to support@web3.storage, rather than admin@web3.storage.
I considered changing all the associated mentions of "admin" (e.g. "adminUser") to "support" as well, but I don't think it's worth it for the amount of disruption it would cause, and "admin" is still a valid label, we're just changing the email address.

chore: send list of storage quota violators to support@web3.storage

---

packages/api/src/env.js

I assume this is a typo?
@adamalton can you also look into this logger running during testing in CI?
https://github.com/web3-storage/web3.storage/runs/6553500624?check_suite_focus=true

fix: typo in Logging constructor

---

packages/api/README.md
packages/website/README.md

Updating the readme to address a few issues I found when setting up the project. 
- When running the API using the readme in `packages/api/README.md` I missed the DB  _"Load schema"_ step resulting in some confusion when trying to log in. Thought I'd add this context in the API readme.
- I got a little confused when running the website, I didn't realise running my env vars for "for local debugging API" meant I'd be using the mock API and not my local API, so updated some text here.
Hope that's okay!
Thanks

chore: update API and Website Readmes

---

packages/api/src/utils/logs.js
packages/api/test/cors.spec.js

This is a follow-up from #1329, adding a test for the functionality that I broke. But it warrants a bit more explanation…
* The `envAll` middleware attaches a `Logging` instance to `env.log`. This should be a new instance for each request.
* The `corsOptions` function is not a middleware in the eyes of the itty-router, because it returns a response, and so the router then skips all other middlwares and just returns that response. This means that, if `corsOptions` is registered before `envAll` then the `Logging` instance is never attached to `env.log` and so when our main `fetch` function tries to call `env.log.end(response)` it dies trying to access the non-existent `env.log` property.
* BUT!... that problem only occurs if the OPTIONS request is the first request made to the server. If a …

chore: add test for CORS OPTIONS handler

---

.github/workflows/cron.yml

This [PR](https://github.com/web3-storage/web3.storage/pull/1371) did not create a related cron release.
At the moment we trigger the cron test and release workflows on `packages/cron/**` and `.github/workflows/cron.yml`.
All cron conf changes should trigger it to make sure updates to those files create a new release.

chore: trigger crons workflow on conf change

---

packages/api/src/auth.js
packages/api/src/constants.js
packages/api/src/errors.js
packages/api/src/index.js
packages/api/src/user.js
packages/db/postgres/migrations/012-add-HasDeleteRestriction-user_tag.sql
packages/db/postgres/tables.sql

* Adding the type and failing HTTP DELETE operations if this tag is set.
* See nftstorage/admin.storage#66

feat: Adding HasDeleteRestriction user_tag

---

packages/api/src/index.js

Not sure if this will fix the error but it's worth a try and feels unlikely to break anything.
Reading through [this](https://github.com/web3-storage/web3.storage/pull/1331) it sounds as though env is **not** a new object for each request 😱

fix: clone env so new each request

---

packages/db/postgres/migrations/012-user_tag_proposal.sql
packages/db/postgres/tables.sql

nft PR [here](https://github.com/nftstorage/nft.storage/pull/1402)
* Users create records in this table and admins manage it.

feat: DB schema and API for user_tag_proposal.

---

package-lock.json
packages/website/.eslintrc.js
packages/website/.prettierrc
packages/website/assets/illustrations/blobs.js
packages/website/assets/illustrations/ring.js
packages/website/assets/illustrations/squiggle.js
packages/website/components/account/fileUploader/fileUploader.scss
packages/website/components/card/card.scss
packages/website/components/cloudflareImage.js
packages/website/components/footer/footer.scss
packages/website/components/hero-illustration.js
packages/website/components/hero/hero.js
packages/website/components/hero/hero.scss
packages/website/components/imageblock/imageblock.js
packages/website/components/navigation/navigation.scss
packages/website/declaration.d.ts
packages/website/modules/docs-theme/index.scss
packages/website/modules/docs-theme/sidebar/sidebar.scss
packages/website/tsconfig.json

This PR is based on #1361 and should be merged to it directly not main! The changes in this PR should serve as a reference to be applied to the rest of the code, see notes below. 
- fix css urls for illustrations, there was several bad urls in css should probably check if the visuals are still good!!
- new cloudflare image loader that works in dev, preview urls and production.
- new HeroIllustration comp with good defaults and for hero images 
Notes:
- All images should be imported and not hardcoded as string paths
- HeroIllustration comp should be used instead of the per image component
- Local images should not have hardcoded width and height, these should come from the images import
- Per illustration component should be deleted in favor of HeroIllustration or similar.

fix: cloudflare loader in #1361

---

packages/cron/README.md

This is really just an inconsequential change to allow the creation of a "fix:" PR so that the release-please bot will make a release.
The reason for this is that #1405 was accidentally named with a "chore:" prefix rather than a "fix:" prefix, and so when it was merged the _release-please_ bot didn't create a release. I considered several possible ways to rectify this, but this solution seemed like the least messy: just create a new PR with a "fix:" prefix which makes an inconsequential change.
Hence, this branch name is prefixed `chore/` (because the change is insignificant), but this PR is prefixed "fix:" so that we now get a release generated for releasing #1405!

fix: optimise getUserByStorage query to avoid timeouts

---

packages/api/wrangler.toml

- Simply updated wrangler.toml with my a development environment var for Josh.

chore: add Wrangler worker env for Josh

---

packages/cron/package.json

As with the other cron jobs, without this we get a connection error.
We might want to address this more properly at some point.

chore: use NODE_TLS_REJECT_UNAUTHORIZED=0 env var for storage cron job

---

packages/website/pages/docs/reference/http-api-manual.md

docs: clarify payload size limit for /car endpoint

---

.github/workflows/api.yml
.github/workflows/website.yml
package-lock.json
package.json
packages/api/package.json
packages/api/test/hooks.js
packages/api/wrangler.toml

This PR upgrades wrangler to its v2. Simplifies API worker configuration ~~and allows us to deploy to cloudflare pages~~.
Some details on our wrangler migration also based on https://developers.cloudflare.com/workers/wrangler/migration/migrating-from-wrangler-1/
```
- 😶 Ignored: "type":
Most common features now work out of the box with wrangler, including modules, jsx,
typescript, etc. If you need anything more, use a custom build.
- Deprecation: "build.upload.format":
The format is inferred automatically from the code.
- Deprecation: "build.upload.main":
Delete the `build.upload.main` and `build.upload.dir` fields.
Then add the top level `main` field to your configuration file:
```
main = "dist/worker.mjs"
```
- Deprecation: "build.upload.dir":
Use the top level "main" field or a …
```

fix: upgrade wrangler

---

packages/api/src/utils/tags.js
packages/db/db-client-types.ts
packages/db/index.d.ts
packages/db/index.js

This just tidies up the typedefs for some of the user tag related functions where were changed/added in #1322, and also improves the function signature of the `createUserTag` function.

chore: fix typedefs for user tag functions

---

README.md
packages/api/README.md

it's not super fun to have to read multiple readmes to get a project started.
Inspired by @joshJarr in #1353  this PR pulls the minimum steps to get a working set up into the main and api readme.

docs: make readmes more self contained

---

packages/cron/src/bin/dagcargo-sizes.js
packages/cron/src/bin/metrics.js
packages/cron/src/bin/storage.js
packages/cron/src/lib/utils.js
packages/cron/test/cargo.spec.js
packages/cron/test/storage.spec.js

I suspect the current jobs that use a direct connection to a RO/RW instances of the DB aren't currently working.
If we take `Populate Missing Content DAG Sizes` as an example you can see that only the initial log (before any DB operations is logged). [Here](https://github.com/web3-storage/web3.storage/runs/6852404133?check_suite_focus=true)'s  an example.
As you can see only 
```2022-06-12T20:44:29.213Z dagcargo:updateDagSizes 🎯 Updating DAG sizes for content inserted after 2022-05-12T20:44:29.212Z```.
No other logs are present (ie `✅ Done`)
I suspect that's because we're not explicitly connecting something fails, not sure why that silently though, I'd expect `query` to raise ( I haven't actually dig deeper in the pg client code to check the actual problem).
Refactor `getPg` to try to …

fix: update getPg to automatically connect to the db

---

packages/api/src/index.js
packages/api/src/temporary.js

This is for testing whether the strange behaviour that's described in #976 is still occurring on Cloudflare.

chore: add API endpoint to test instanceof behaviour on Cloudflare

---

packages/website/pages/_app.js
packages/website/styles/global.scss
packages/website/styles/layouts/pageContainer.scss

Closes https://github.com/web3-storage/web3.storage/issues/1440
Switches the "callback" route to product-app to fix the background
Uses flexbox to position the footer for product-app

fix: login screens jarring

---

packages/cron/src/jobs/storage.js
packages/db/postgres/functions.sql
packages/db/postgres/migrations/015-update-user-by-storage-used.sql
packages/db/postgres/migrations/016-add-upload-user-id-index.sql
packages/db/postgres/pg-rest-api-types.d.ts
packages/db/postgres/tables.sql

Previously we were using ID ranges. But the IDs of rows in the `public.user` table are not consecutive/sequential. So when we tried this on staging it went a bit like this:
1. Lowest user ID is 5, highest user ID is 314286764840715234.
2. It splits that range into chunks of 1000, giving us over 300 trillion batches to work through, just to iterate over 79 users.
3. The internet melts.
This PR changes the batches strategy to the form `SELECT ... WHERE id > highest_id_of_last_batch LIMIT users_per_batch`., which will hopefully go better.
Given that the `015` migration hasn't yet been run on production, I've modified it, rather than making a new one. It's already been run on staging, but running the modified version should be fine.

fix: change batching strategy for user storage cron

---

packages/cron/src/jobs/storage.js

Testing the query in prod highlighted it can be extremely slow if prod, decreasing the batch size.

fix: make the default batch size for storage limit cron smaller

---

packages/cron/test/hooks.js

chore: increase the timeout for the `beforeAll` hook for cron tests

---

packages/cron/src/bin/storage.js

We should clean after ourself and close the connection to the db at the end of the cron.

fix: close connection at the end of cron

---

packages/website/components/account/filesManager/filesManager.js

You'll need to have a token setup in the API tokens screen + have used the API to pin a file (status has transitioned to "Pinned") in order to see the changes (see https://web3.storage/docs/how-tos/pinning-services-api/)
Before:
After:

fix: pins missing

---

packages/website/components/navigation/navigation.scss
packages/website/modules/docs-theme/index.scss

fixes #1458
This PR fixes a bug where the active state of `/docs` nav item was stuck "on" after the first visit. Also fixes the current state for dark backgrounds adding a light on state underline for active nav items on dark backgrounds.

fix: nav active states

---

.github/workflows/cron-storage-limits.yaml

Increasing the job timeout, as discussed with Vasco, to figure out if that is enough to go through all the users.

fix: increase storage limit job timeout

---

packages/website/content/pages/about.json

Removes the deal polling copy until we make it do that. Shuffles paragraph around to avoid breaking page layout
Fixes: #1042
| before | after |
|--------|------|
|<img width="808" alt="Screenshot 2022-05-30 at 15 47 31" src="https://user-images.githubusercontent.com/58871/171017052-e48c9fae-ca3b-403a-99a4-83b13574292d.png"> | <img width="816" alt="Screenshot 2022-05-30 at 15 45 38" src="https://user-images.githubusercontent.com/58871/171017079-7b56a89f-8c99-4e18-91e0-599f1e117de2.png">

chore: Remove deal polling copy

---

.github/workflows/cron-storage-limits.yaml
packages/cron/src/lib/email/service.js

The staging DB is now a fork of prod that results in duplicated emails if we run the cron from both prod and staging environments.
Let's just log emails are sent in staging.
Tested [here](https://github.com/web3-storage/web3.storage/runs/6969064271?check_suite_focus=true)

fix: use dummy provider in staging

---

packages/client/src/lib.js
packages/client/src/lib/interface.ts
packages/client/test/custom-fetch.spec.js

I need to process some headers, like the cookie. because I post the request to my service and do some validation and then I create a proxy request to forward the request to your server. so, I need to add the `credentials: "include"` option to the `requestInit` option.
therefore, I add the `pre` middleware to achieve that, it will pass the requestInit to the user, and the user modifies and returns it to the client before the request is sent.

feat: js client accepts user provided fetch function

---

packages/client/src/lib.js
packages/client/test/custom-fetch.spec.js

- remove duplicated service options definition, to fix unintended manditory `fetch` property on js client constructor
- remove redundant test from #1324

fix: reuse Service type sig for client options

---

packages/api/src/error-handler.js
packages/api/src/utils/logs.js

The status property is not set to Error that is sent to logs. There is really no point in previous condition where log function had a check for status >= 500 given log function is used for error, warn and regular log. So, Error log should check if is a vaid error to log (500) before asking to log

fix: sentry not receiving errors

---

packages/website/components/contexts/tokensContext.js
packages/website/components/tokens/tokenCreator/tokenCreator.js
packages/website/components/tokens/tokensManager/tokensManager.js
packages/website/components/tokens/tokensManager/tokensManager.scss

fixes #1318 
This PR adds error messaging for the tokens section of the website when the API is in maintenance mode.
- Put the api in maintenance mode [README](https://github.com/web3-storage/web3.storage/blob/main/packages/api/README.md#maintenance-mode)
OR Locally `packages/api/src/maintenance.js ln:29`
- Visit `/tokens/` and `/tokens/?create=true`
- NO_READ_OR_WRITE will show error message for creation and retrieval of tokens
- READ_ONLY will successfully show tokens but show error when creating a new token

fix: explain api maintenance mode

---

packages/website/components/account/filesManager/filesManager.js

If delete file fails, the app kinda breaks.  Delete file will fail when the user has delete restriction.  This just catches and ignores any errors so that the modal closes gracefully
Closes #1409

fix: allow delete file modal to close on error

---

packages/website/components/tokens/tokenCreator/tokenCreator.js

It looks like the href on this button was likely an accident originally, but my recent changes to the button component exposed it as a problem.
Closes #1520

fix: stop navigating to account screen from token creator button

---

packages/db/postgres/migrations/016-add-upload-user-id-index.sql
packages/db/postgres/migrations/018-drop-upload-user-d-index.sql
packages/db/postgres/tables.sql

With index added in https://github.com/web3-storage/web3.storage/pull/1466 this should not be needed, as it includes it and also has optimization for not deleted

fix: drop uploads user index

---

packages/db/postgres/migrations/019-create-pin-content-cid-index.sql
packages/db/postgres/tables.sql

Create an index on `pin(content_cid, status)` to speed up `user_used_storage` joining and filtering.
I'll create a separate issue to audit the use of `CREATE INDEX IF NOT EXISTS pin_status_idx ON pin (status);` and to verify if it can be dropped in favor of this new one.
[Storage Limit Email Notifications Storage Limit Email Notifications #43](https://github.com/web3-storage/web3.storage/runs/7074203706?check_suite_focus=true) ran on staging in 11 minutes. ( staging amount of data is now comparable to prod).
🛑  The index has already been created in STAGING to test the performance against a large amount of data.

fix: optimise pin content cid query

---

.env.tpl
.github/workflows/cron-dagcargo-sizes.yml
packages/cron/README.md
packages/cron/src/lib/utils.js
packages/cron/test/cargo.spec.js

We already have CARGO secrets in Github, let's build the connection string out of those instead of having a new one.

fix: build-cargo-connection-string

---

packages/website/modules/docs-theme/index.js
packages/website/modules/docs-theme/toc/toc.js

Resolves an issue where, after docs links were tested and modified to use absolute paths, they all triggered a page reload. Because all links paths start with `/docs/foo`, they are treated as regular links that the client handles, rather than Next's built-in virtual routing.

fix: no page reload when pointing to relative path in docs

---

packages/cron/src/jobs/dagcargo.js
packages/cron/test/cargo.spec.js

In SQL comparisons with null are a bit funky,
Given this query
```
SELECT d.cid_v1 as cid, d.size_actual
FROM cargo.dag_sources ds
JOIN cargo.dags d using ( cid_v1 )
JOIN cargo.sources s USING ( srcid )
WHERE
d.size_actual > 0 AND 
d.size_actual != ds.size_claimed AND 
ds.entry_last_updated > $1 AND
s.project = 1
LIMIT $2
OFFSET $3
```
is wouldn't actually select rows with d.size_actual= 10 and  ds.size_claimed=null. While we should make sure those content rows do get updated.

fix: make sure null claimed sizes are updated

---

.github/workflows/cron-dagcargo-sizes.yml
packages/cron/src/bin/dagcargo-sizes.js
packages/cron/src/jobs/dagcargo.js
packages/cron/test/cargo.spec.js
packages/db/test/utils.js

In this #1535 we moved to use a direct connection to cargo to avoid expensive FDW cross-joins.
As you can read in the [PR](https://github.com/web3-storage/web3.storage/pull/1535) description we also assumed cargo would pull the updated `claimed_dag_size`.
Unfortunately, that is not the case and that means we are updating the same content multiple times, despite it having been already fixed by the previous run.
While more optimized solutions exist, given this runs in a cron job and we've been changing it so many times, I'm going with a naive solution here, where I just update dag size if it has changed. 
That means we still have a go through lots of content that should really be looked at. 
However, this shouldn't be a big problem, given this happens in a cron, and we mostly run this on …

fix: update content dag_size only if it has changed

---

.github/workflows/cron-dagcargo-sizes.yml
packages/cron/src/bin/dagcargo-sizes.js

A few quick wins to improve dag size job:
- run in prod only (both staging and prod run against the same cargo replica, let's avoid adding unnecessary load)
- still able to run against staging manually 
- run on a shorter time frame by default
- longer timeout for manual distpatch to be able to run in against longer timeranges

feat: dag size job improvements

---

.github/workflows/cron.yml

We noticed DB changes did not trigger cron tests and cron uses DB, so it should

fix: cron test should run on db change

---

packages/client/src/lib/interface.ts

The first example given [here](https://www.npmjs.com/package/web3.storage) fails with this error:
>Argument of type '{ token: string; }' is not assignable to parameter of type 'Service'.
Property 'endpoint' is missing in type '{ token: string; }' but required in type 'Service'.ts(2345)
interface.d.ts(14, 5): 'endpoint' is declared here.
It looks like the type declaration for the Web3Storage constructor declares the options parameter type to be Service in the JSDoc and this gets picked up on for the TypeScript declaration.  This is one possible strategy which might fix it.

fix: Make endpoint optional in Service interface

---

package-lock.json
packages/cron/src/jobs/pins.js

Diagnosed locally https://github.com/web3-storage/web3.storage/issues/1651 and got the underlying error throwed by pgrest: 414 URI Too Long response status code 
This seems a consequence of IDs of PINs increasing to a point where they have more digits resulting in a larger URL with query parameters. Reducing to 500 immediately ran for me locally
Once merged:
Closes #1651

fix: cron pins delete

---

packages/cron/src/jobs/pins.js

Our cron job is writing remote status pins in the table...

fix: cron pins skips remote status

---

.github/workflows/delete-remote-pins.yaml
packages/cron/package.json
packages/cron/src/bin/delete-remote-pins.js
packages/cron/src/jobs/delete-remote-pins.js

Brings back job from https://github.com/web3-storage/web3.storage/pull/1615 because of regression introduced with cron job https://github.com/web3-storage/web3.storage/pull/1660

chore: bring back cron to remove remote status pins

---

packages/website/content/pages/contact.json

fixes #1667
This PR updates links to the slack and discord icons and removes redundant links.

fix: links to slack and discord

---

packages/website/pages/docs/intro.md

fix: properly direct user to /tokens instead of /account for token creation

---

packages/website/components/account/fileUploader/fileUploader.js
packages/website/modules/zero/components/dropzone/dropzone.js

Closes #1552 
Adds a tooltip next to the "Failed" text on file uploads that displays the error from the API.

feat: add error tooltips to file uploader

---

.github/workflows/cron-pins.yml

This cron job timeouts once in a while https://github.com/web3-storage/web3.storage/actions/workflows/cron-pins.yml. Let's use 15min instead

fix: increase cron pins timeout to 15 mins

---

packages/cron/src/jobs/pins.js

It was still possible for the cron to write Remote status given status variable could be changed for it. Ran today the delete job and found a few more that came from there https://github.com/web3-storage/web3.storage/runs/7496383579?check_suite_focus=true#step:6:43

fix: cron remote status

---

packages/website/components/tokens/tokenCreator/tokenCreator.js
packages/website/components/tokens/tokenCreator/tokenCreator.scss
packages/website/components/tokens/tokensManager/tokensManager.scss
packages/website/pages/tokens/index.js
packages/website/pages/tokens/index.scss

closes #1608
The api tokens header is redundant especially on mobile. This PR changes the view from:
to this improved version here:
I also fixed a bad link in the footer which had nested link tags:
Also changed the input button to use icons to avoid baseline issues with the font "+" so that it is correctly centered.

fix: overlap on token creator and a few mobile issues

---

.github/workflows/cron-storage-limits.yaml

The `Storage Limit Email Notifications` workflow use stategy matrix (as other worflows in the project, ie metrics, cron-pins etc) to run against different environments.
That's cool, however, by default strategy has `fail-fast: true` and that means all jobs are cancelled if one in the workflow fails.
This practically means that if staging fails prod is skipped/cancelled, creating a dependency/coupling between the 2 environments we don't want.

fix: limit production job should not fail if staging one fails

---

.github/workflows/cron-names.yml
packages/cron/package.json
packages/cron/src/bin/names.js
packages/cron/src/jobs/names.js
packages/db/index.js

This script will run as a CRON job to push name records to w3name.
If the record was already migrated or superseded you will see the following error message `400 Bad Request {"message":"invalid record: the record is outdated."}` otherwise `202 Accepted {"id":"k51qzi5uqu5dkf4iy7zpxjasuk2b6x4wqr9vp7cd8m3x2kdlav02ppw9d9ulwf"}`.

chore: ipns record migration to w3name

---

packages/api/src/error-handler.js
packages/api/src/errors.js
packages/api/src/index.js
packages/api/test/auth.spec.js
packages/api/test/pin.spec.js

Resolves #1320
In investigating the issue above, we discovered that the pinning service API was not compliant with the IPFS Spec when throwing errors. Hence, why for the CLI, there were no errors shown.
To make the pinning service compliant with the spec (found [here](https://ipfs.github.io/pinning-services-api-spec/#operation/getPins)). I have nested the error and updated the properties to `reason` and `details`. I have updated the tests to match the specification.
The logic to decide whether we should use the IPFS style errors is in the error handler and based on the request path.
This seemed like the cleanest way to do it, but please let me know if you have other ideas.
@flea89 and I came up with other solutions:
1. Pass a "type" to the middleware that checks for PSA Authorization and …

fix: Make PSA Errors compliant

---

.github/workflows/api.yml
.github/workflows/client.yml
.github/workflows/cron.yml
.github/workflows/db.yml
.github/workflows/w3.yml
.github/workflows/website.yml

We already had regressions in the past because package lock was updated and it did not trigger tests of all the packages. This also brings other issues as workflows are not triggered like https://github.com/web3-storage/web3.storage/commit/000e4dcd9e1119361c29c0dad851a5ea6d6db1b5

fix: run tests in jobs on package-lock change

---

packages/website/components/account/filesManager/fileRowItem.js

This PR changes gateway link on files table to w3s.link instead of dweb.link
Needs #1728

feat: add w3s.link url on files table

---

packages/website/pages/docs/concepts/w3link.md
packages/website/pages/docs/how-tos/retrieve.md
packages/website/pages/docs/nav.json

This PR adds docs for w3link. For now, it is a copy of https://nft.storage/docs/concepts/gateways/ with minimal changes (i.e NFT -> Web3)
Preview: https://99bdf644.web3-storage-staging.pages.dev/docs/concepts/w3link/

feat: w3link docs

---

packages/cron/src/lib/email/README.md

Resolve #1506 
As part of this I update the templates in Mailchimp, please review.
At the moment updating email styles and templates is quite painful, I've timeboxed this to the quick wins:
- casing, :white_check_mark: :white_check_mark:
- logo :white_check_mark: :white_check_mark:
- round-corners :white_check_mark: :white_check_mark:
- Padding adjusted, it’s not the same but closer…  I think it now has a better balance
- Title, I think left aligned looks better
- Haven't changed the email to show the quota, given it requires changing the jobs and it was deemed as not worth it by David
Once reviewed, I will export to mandril and to the required changes.

feat: update email docs

---

packages/cron/src/jobs/names.js

Noticed something a little off with the URL patterns, this should correct it!
Notes for reviewer(s): Worth ensuring these variables are being used correctly too

chore: correct w3name staging and prod urls in cron job.

---

packages/website/.eslintrc.js
packages/website/pages/_app.js
packages/website/pages/account/payment.js
packages/website/tests/accountPayment.e2e.spec.ts
packages/website/tests/homepage.e2e.spec.ts
packages/website/tests/screenshots.ts
packages/website/tsconfig.json

Motivation:
* https://github.com/web3-storage/web3.storage/issues/1698
* establish /account/payment page
* add test ensuring that anons accessing /account/payment are redirected to /login/ - good thing to monitor for regressions, at least until we have better tests
Note
* nothing's in there yet. We'll add to it over time.
* e2e test of logged in state requires some research https://github.com/web3-storage/web3.storage/issues/1749
closes #1698

feat(@web3-storage/website): add /account/payment page in website

---

packages/website/modules/docs-theme/feedback/feedback.js
packages/website/modules/docs-theme/feedback/feedback.scss

This is just using the latest deploy date for the "last updated on" date but that's not correct.  Since we don't have a good way of pulling when a specific *page* was updated, we're just going to remove this date for now.
closes #1549

fix: remove incorrect 'last updated on' text

---

packages/api/src/auth.js
packages/api/src/env.js
packages/api/src/index.js
packages/api/src/magic.link.js
packages/api/src/user.js
packages/api/test/contexts/authorization.js
packages/api/test/hooks.js
packages/api/test/user-payment.spec.js

Motivation
* @cmunns is gonna use this in https://github.com/web3-storage/web3.storage/issues/1741
What
* add the route
* it always returns the same thing
* I'll add a way of mutating it in followup PR
* test that this route requires auth
* hide 'test-magic' details from the test via new AuthorizationTestContext
* mocha hooks installs this context
* tests can use the context to `createUserToken()`
* provides abstraction on how our tests get an authz token
* followup pr can replace other repeated instances of 'test-magic' with `createUserToken()` https://github.com/web3-storage/web3.storage/search?q=test-magic

feat: add to api GET /user/payment, add AuthorizationTestContext to encapsulate magic.link test bypass

---

.github/workflows/website.yml
packages/website/components/loading/loading.js

Note:
* non-main pr target
Motivation:
* experimenting with solution for: https://github.com/web3-storage/web3.storage/pull/1754#discussion_r951279621

ci: build website doesnt use dotenv/config

---

.github/workflows/api.yml
.github/workflows/website.yml

Once this is merged, the `CF_API_TOKEN` secret can (and should) be deleted from this repo's secrets.

chore: switch to org-level GH secret for Cloudflare token

---

packages/api/src/auth.js

Was getting an error on staging when logging in:
```
{"code":"ERROR_MAGIC_TOKEN_REQUIRED","message":"Must be logged in with magic.link"}
```
Looks like the issuer wasn't being passed correctly, this PR hopefully resolves this!🤞

fix: return correct issuer from magic token in `tryMagicToken`.

---

packages/w3/index.js

Makes more sense for our `w3` command to offer the user a link to our w3s.link gateway.
```bash
❯ w3 put olizilla.png --no-wrap
⁂ Stored 1 file
⁂ https://w3s.link/ipfs/bafkreiawm5lgdgchgrhep4kxo2g4tptewtpcnfzusyfcopytpuj2fnzf2m
```
License: MIT

feat: `w3` command using w3s.link

---

packages/website/pages/docs/how-tos/retrieve.md

This adds a callout to the retrieval docs that acknowledges that the current situation isn't great, but we're working on a fix.

chore: add note about client.get reliability to retrieval doc

---

.github/workflows/w3.yml

This undoes the manual setting of the version number and previous release commit sha in the release-please config for the `w3` package, which was added in #1799.
Once we've merged this **and** done another successful release of the `w3` package, we can call #1789 done. (Although maybe we just close #1789 and re-open it if something bad happens next time, as I don't think there are any other pending changes for `w3` that are likely to be released imminently.)

chore: remove manual settings of release version for w3 package

---

packages/api/test/car.spec.js
packages/api/test/hooks.js
packages/api/test/maintenance.spec.js
packages/api/test/user-payment.spec.js
packages/api/test/user.spec.js
packages/api/tsconfig.json

Motivation:
* followup to https://github.com/web3-storage/web3.storage/pull/1813
* in that pr I didn't notice that `./test` dir would not be typechecked. This adds that

feat: packages/api typecheck checks ./test dir

---

packages/website/components/hero/hero.js

fix: remove helix image that clashes with 'products' nav item

---

packages/api/package.json
packages/api/scripts/cli.js
packages/api/src/env.js
packages/api/test/hooks.js
packages/api/wrangler.toml

the errors are now showing up in sentry with `abs_path: "orker.js"` which looks like we are trimming a w from `worker.js`.
that also suggests the file is now renamed worker.js by wrangler v2 on upload, so we rename ours in this PR.
- `worker.mjs` -> `worker.js` to match what we see in sentry error.
- stop stripping first char on paths in stack traces in sentry client config.
- set `rewriteFrames.root: '/'` to get toucan to prepend `/` to make it `/worker.js`
see: https://github.com/web3-storage/web3.storage/pull/1033
needs: https://github.com/web3-storage/web3.storage/pull/1731
replaces: https://github.com/web3-storage/web3.storage/pull/1593
License: MIT

fix: sourcemap stacktraces in sentry

---

packages/api/src/upload.js

This is currently raising alerts for on call folks but is a client error.

fix: empty payload is client error

---

.github/workflows/website.yml
packages/api/src/utils/stripe.js
packages/api/test/stripe.spec.js

Motivation:
* small errors in /account/payment in staging/prod
Why wasn't this caught by testing?
* missing env var - I should have tested the website preview link
* uncaught error - this is tricky. We mock this service in all our tests, so tests wouldn't have caught it. Maybe test code coverage metric could have helped.  We can also later consider running e2e tests against a stripe account in testMode (instead of mocks)

fix: /account/payment tiny bugs - use env var on website, fix uncaught error when no default_payment_method in StripeBillingService

---

.github/workflows/website.yml
packages/website/lib/countly.js
packages/website/rawJsFromFile.js
packages/website/tests/accountPayment.e2e.spec.ts

Motivation
* e2e tests often hang while the orchestrated web browser is waiting for requests to 'cdn.amplitude.com' or 'browser-update.org'. Sometimes these requests take a long time (the only reason I can think of is maybe the e2e orchestrated browser has a very fresh cache or something). I don't think we need to load those scripts when running the app on `localhost` (e.g. in tests), so this PR disables them. I think it will lead to more reliable CI at no real cost.
* I think the website ci workflow 'release' step never ran after this merge https://github.com/web3-storage/web3.storage/pull/1866
* I think because the e2e tests timed out, so the 'release' job never ran.
* Hopefully this PR fixes the e2e test time out. But I also added a workflow input we can use to re-trigger the release …

fix: make website e2e tests more reliable on ci

---

packages/api/scripts/generate-upload-data.js

Adds a script that generates a number of uploads and optionally generates pins to be used when testing large sets of paginated data.

chore: add a script that generated many uploads

---

packages/website/rawJsFromFile.js

The [browser update library](https://browser-update.org/), which was added in #1080 to address Internet Explorer related QA issues, was set to relative browser versions (e.g., Firefox was set to _two major version ago_). 
This created an issue where browsers that were still modern but slightly out-of-date would prompt the dialog box telling the user to update their browser.
This PR adjusts to absolute versions for the browser update library instead of the relative format. The following were set as thresholds for the dialog box to appear:
- IE/Edge < 11
- Firefox < 95
- Opera < 80
- Safari < 10
- Chrome < 96

fix: make browser update versions absolute

---

package-lock.json
packages/w3/README.md
packages/w3/bin.js
packages/w3/package.json

I find myself having to add the https://w3s.link/ipfs prefix a lot. I want a command to do it for me.
```bash
w3 open bafybeidluj5ub7okodgg5v6l4x3nytpivvcouuxgzuioa6vodg3xt2uqle
w3 open bafybeidluj5ub7okodgg5v6l4x3nytpivvcouuxgzuioa6vodg3xt2uqle/olizilla.png
```
License: MIT

feat: `w3 open <cid>` to open cid on w3s.link in browser

---

packages/db/postgres/migrations/024-add-index-upload-type.sql
packages/db/postgres/tables.sql

We compute metrics in cron metrics based on upload type. As our upload table is getting bigger and bigger, this has become an issue. Adding an index for type to enable fast queries using that row

fix: db index upload type

---

packages/website/pages/docs/how-tos/store.md

@ribasushi reminded me that we could really use an example of POST-ing a CAR directly to the API.
This adds a new tab to the "Storing IPFS Content Archives" section of the Store how-to with a few examples, and a callout to use `--data-binary` instead of `-d`.

chore(docs): add curl CAR upload example to store howto

---

package-lock.json
packages/api/package.json
packages/api/src/car.js

it's hot off the press but _some nice folks in a discord_ **assure** me that `sha256` checksum verification is available for `r2.put`
- remove md5 dep and use sha256 from carCid as we do for putToS3.
- tweak method signatures to take the env, so they can be pleasingly symetrical.
- capture the `rootCid` and `carCid` in the metadata so when we want to make object keys the same across s3&r2 at least we'll have both hashes in the meta, regardless of the key structure. 
see: https://community.cloudflare.com/t/2022-9-16-workers-runtime-release-notes/420496 see: https://discord.com/channels/595317990191398933/940663374377783388/1021788854388281477
License: MIT

feat: use sha256 checksum for r2.put

---

packages/api/src/car.js

The `sha256` string we pass to `r2.put` should be hex.
tested on staging. it work.
License: MIT

chore: encode sha256 hash as hex for r2 put

---

packages/db/postgres/migrations/024-replace-create-content-fn.sql

remove last step in `create_content` fn where we create new `pin_sync_request` rows. These are no longer needed as we ask linkdex-api to determine dag completeness over CARs in S3.
This migration applies just the change we expect to the `create_content` fn. I could reapply the entire functions.sql, but it felt wise to scope the db change down as much as possible.
The plan is to release https://github.com/web3-storage/web3.storage/pull/1884 which will mean we no longer write to cluster and update the `create_content()` fn to stop creating `pin_sync_request` rows, then let the existing `pin_sync_request`s get processed, then remove the pin sync cron job.
This change has been applied to the staging db `web3-storage-staging-0`
see: https://github.com/web3-storage/web3.storage/pull/1785 …

chore: db migtation updating create_content fn

---

packages/api/src/car.js
packages/api/src/utils/logs.js

- add timers for `putToR2` and `putToS3`
- tweak logger to send the timers as metadata to logtail so we may chart it.
- fix tsc errors in log.js
This updates the final request log we send to logtail to include a `timers` property, with a key for each timer name and it's duration in `ms`.
```js
{
message: '',
dt: '2022-09-20T14:02:42.960Z',
level: 'info',
metadata: {
user: { id: '1' },
request: {
url: 'http://127.0.0.1:8787/car',
method: 'POST',
headers: [Object],
cf: [Object]
},
cloudflare_worker: {
version: '7.5.1',
commit: 'eae75d2366d59b0cf16143723a5af6513d891f9e',
branch: 'main',
worker_id: 'krXpoggAwV',
worker_started: 1663682561602
},
timers: { putToR2: 237, putToS3: 464, request: 494 },
response: { headers: [Object], status_code: 200, duration: 494 }
}
}
```
License: MIT …

feat: send timing info to logtail. Time r2 & s3.

---

.github/workflows/api.yml

Motivation
* I shouldn't have moved so fast in adding this. It didn't work, and I missed that it didn't work in main, so also release-pleased to prod, and I think now the api workflow will always be broken for api releases, which is gross.
* This ci part isn't critical and I'm on a deadline, so I will improve things later by continuing ci work via [this](https://github.com/web3-storage/web3.storage/pull/1929), but not for a week or two

chore: rm stripe.com:fixtures stuff from api workflow, it doesn't work

---

package-lock.json
packages/api/package.json

adopt our forked toucan-js so we can start reporting error causes to sentry
i've set up a minimal fork over here with our standard release-please publishing flow: https://github.com/web3-storage/toucan-js
the original PR that i want to get deployed is here https://github.com/robertcepa/toucan-js/pull/104
and we've now got that rolled into our own npm package at https://www.npmjs.com/package/@web3-storage/toucan-js
License: MIT

chore: report error cause to sentry

---

.github/workflows/website.yml
packages/website/lib/magic.js
packages/website/pages/account/payment.js
packages/website/pages/callback/index.js
packages/website/pages/login/index.js
packages/website/tests/accountPayment.e2e.spec.ts

Motivation:
* Current if you're logged out, then try to access a page that requires auth like /account/payments, you'll be redirected through the authentication process and end up at /account (not the destination you originally wanted, always /account)
What this does
*  /account/login?redirect_to=/final/url should redirect to /final/url after authn
* /account/payment page getStaticProps redirectTo redirects to `/account/login?redirect_uri=/account/payment` so the /pricing page can link to /account/payment

feat: /account/login?redirect_to=/final/url should redirect to /final/url after authn

---

packages/api/src/user.js
packages/api/src/utils/billing-types.ts
packages/api/src/utils/billing.js
packages/api/src/utils/stripe.js
packages/api/test/fixtures/init-data.sql
packages/api/test/stripe.spec.js
packages/api/test/user-payment.spec.js
packages/api/test/user.spec.js
packages/db/db-client-types.ts
packages/db/index.js
packages/db/test/user.spec.js
packages/website/components/account/paymentTable.js/paymentTable.js
packages/website/pages/account/payment.js
packages/website/pages/callback/index.js
packages/website/tests/accountPayment.e2e.spec.ts

* there wasn't previously a way that the api `loginOrRegister` function could determine when a user was created for the first time based on its invocation of `db.upsertUser()`
* now `db.upsertUser()` returns `inserted` boolean in its return value
* when `loginOrRegister` does an `upsertUser()` that results in a new user insert, then it attempts to initialize the new user, e.g. by initializing their storage subscription
* only after this change is it a valid state for GET /account/payment paymentSettings can now come back like
```
{
paymentMethod: null,
subscription: { storage: { price: 'free' } }
}
```
* Previously, there was never a time where subscription.storage would be non-null and also paymentMethod would be null.
* because of that last thing, the previous react hook setup on …

feat: new users are initialized into free tier

---

packages/api/src/user.js

Since #1976 didn't touch any files in the `api` package, it didn't trigger the release-please bot to open a release PR.
This just adds a kind of pointless comment so the change gets picked up.

fix: trigger release to pick up fix from #1976

---

packages/db/index.js
packages/website/components/account/addPaymentMethodForm/addPaymentMethodForm.js
packages/website/components/contexts/plansContext.js
packages/website/hooks/use-payment.js
packages/website/lib/api.js
packages/website/pages/account/payment.js
packages/website/tests/accountPayment.e2e.spec.ts
packages/website/tsconfig.json

Previously, the 'earlyAdopter' plan id would be PUT to the api, but the backend doesn't allow this value as a storage subscription price. The backend doesn't explicitly model 'earlyAdopter' nor 'plans'. But the equivalent is to have a `null` storage subscription, and this commit sends that instead.
This pr also adds type hints that would have prevented this bug from being introduced, and will hopefully help in the future.

fix: fix bug when saving payment method while paymentSettings.storage.subscription=null

---

packages/api/src/user.js
packages/db/db-client-types.ts
packages/db/index.js
packages/db/postgres/functions.sql
packages/db/postgres/migrations/027-change-upsert-user-return-type.sql

Motivation:
* originally I typed [UpsertUserOutput.id as a number](https://github.com/web3-storage/web3.storage/pull/1945/files#diff-3f447b347f942bfd2bcfa962fec4f2320ea8ef5e7c759367d7071da5af108d0aR16), but in the db these ids are bigints which will overflow js Number.MAX_SAFE_INTEGER

fix: migrate upsert_user function to return id text instead of id bigint

---

packages/website/components/general/metadata.js

Closes #1984 
I'm not familiar with `<meta property="image" content="/social-card-web3storage.jpg" />` and googling gave me nothing, so I'm just yanking it out.  Let me know if this one rings a bell for anyone.

fix: fix social media preview image URLs

---

packages/website/content/terms-of-service.mdx

Adds terms for w3link per feedback on https://github.com/web3-storage/web3.storage/issues/2008
It includes same content as https://nft.storage/terms/#gateway (just swapped nft for w3link)

fix: add terms for w3link usage

---

packages/website/pages/pricing.scss

https://www.notion.so/Make-get-started-on-Pricing-Page-more-easily-clickable-it-doesn-t-light-up-unless-your-cursor-hi-0f1e6f42515d46b88daca24ae1468565
The issue was the image was overlaying the button:
Proposed fix:
Disable `pointer-events` for the image so the browser acts like the image doesn't exist when you click where they overlap.
Post fix:

fix: "get started" only partially clickable

---

packages/website/components/account/storageManager/storageManager.js

Image below helps with verification of bar progress.

feat: tie in currentPlan into storage useage meter

---

packages/website/components/contexts/authorizationContext.js
packages/website/components/general/restrictedRoute.js
packages/website/components/types.d.ts
packages/website/pages/account/payment.js
packages/website/tests/accountPayment.e2e.spec.ts

https://www.notion.so/Ensure-redirect-from-Pricing-page-takes-you-to-post-login-modal-of-selected-tier-e9fb5131d7b2486596de0d8c17f77161
This PR is a follow up to a conversation BenGo (not tagging him here to avoid notification noise) and I had a couple of weeks ago.  The high level summary is:
Something like the pricing page could use a `requiresAuth: true` behavior.  This would function similar to the `redirectTo: '...'` behavior, except it would capture the url and handle the redirecting automatically.  This is important for tiered pricing because otherwise we can't include which tier the customer selected on the public pricing page before we redirect to the authenticated accounts payment page because the `redirectTo` must be static.

fix: login redirect should preserve query parameters

---

packages/api/src/user.js
packages/api/src/utils/billing-types.ts
packages/api/src/utils/billing.js
packages/api/src/utils/stripe.js

Currently when customers are added to stripe, their name and email are missing.  This makes it difficult for the business to evaluate issues, since we'd need to look at our own database to determine which web3.storage user is associated with a stripe customer.

feat: display name and email in stripe

---

packages/website/components/breadcrumbs/breadcrumbs.js
packages/website/components/footer/footer.js
packages/website/components/link/link.js

Motivation:
* CIC - this was at top of CIC backlog for the repo
* https://github.com/web3-storage/web3.storage/issues/2006
How?
* made it so the go-to website `<Link />` component will enforce the logic @jchris requested

feat: website link component defaults target to _blank when the href is external

---

packages/website/components/accountPlansModal/accountPlansModal.js
packages/website/pages/account/payment.js

This shows the user the plan they wanted from the home page after logging in.

feat: show tier modal on account page after logging in

---

packages/website/components/loading/loading.js

Closes #2002 
Context: center aligns the loading icon within login/logout button

fix: properly center align the loading icon within login/logout button

---

packages/api/src/car.js

add metadata to upload error reports in sentry so we can debug when we see an uptick in concurrent upload errors.
the `sentry.addExtras` function lets us set additional metadata on error reports and shows up like the screenshot below:
> setExtras: Set an object that will be merged sent as extra data with the event.
– https://github.com/robertcepa/toucan-js#features
License: MIT

feat: add metadata to upload error reports

---

packages/api/src/car.js

dont report it as a CID object, as they look whack. e.g.
License: MIT

fix: report carCid as string to sentry

---

.github/workflows/api.yml

Update the api workflow so that the prod deploy job only runs on main and if there is a release created flag from release_please
This brings the api workflow inline with the website one: https://github.com/web3-storage/web3.storage/blob/53e6da1dd62831f85735ed2b403427e731ee863d/.github/workflows/website.yml/#L242
this should prevent weird deploys happening just due to a timing error, and means we wont see a github deployment for non-main api builds... note: we will still lots of prod deploy builds as we also provide the production env to website builds, and github doesn't know about out api vs website distinction.
License: MIT

fix: ensure prod api deploy can only happen from main

---

packages/api/test/user.spec.js
packages/db/index.js
packages/db/postgres/functions.sql
packages/db/postgres/migrations/030-decouple-user-used-storage.sql
packages/db/postgres/tables.sql
packages/db/test/user.spec.js
packages/db/test/utils.js
packages/db/utils.js

This PR aims to optimize performance for calculating user used storage. It includes:
- decouple `user_used_storage` into 2 functions, one for regular uploads and other for psa
- both regular uploads and psa now ignore Pin status. If it is not Pinned, we won't know the dag size.
- this should be a big boost given Pin table is by far the largest table we have
- an accepted side effect by us is that non completed uploads that get stalled will be accounted
- changes psa sql indexes so that a sequential scan is avoided
- seq_scan on psa_pin_request is done to check the deleted_at and to join with auth_key table
- `psa_pin_request_search_idx` should perform better and includes the 3 columns used
- other psa indexes were only used in this flow

perf: decouple user used storage sql function

---

packages/website/pages/index.scss

fix: align links when stacking mobile

---

packages/website/content/pages/general.json

'web apps' in footer linked to terms, needed removal.

fix: remove web apps footer link

---

.github/CODEOWNERS

Motivation:
* ensure tech leads for website initiative aren't blocked from merging PRs to main (e.g. to accept code into main branch or to merge release-please PRs)
* followup to #2047 
* https://www.notion.so/add-website-codeowners-team-to-web3-storage-CODEOWNERS-file-for-website-package-7b13982728364e0db4d4778ca21c5807
What:
* I created this `@web3-storage/website-codeowners` team in github: https://github.com/orgs/web3-storage/teams/website-codeowners
* I added @johnathonroach to it who is techleading the website ongoing log initiative
* This PR should make it so code changes to only the website can be approved by anyone in dag-house team or anyone in that website-codeowners team.
Potential followups
* propose/make any changes to who is in @web3-storage/website-codeowners team (I defer …

chore: add @web3-storage/website-codeowners to CODEOWNERS of /packages/website

---

packages/website/pages/docs/how-tos/pinning-services-api.md

closes #2024 by changing the API endpoint from `api-staging` to `api`.

fix: rm staging url in PSA docs

---

packages/website/components/account/accountBlockedModal/accountBlockedModal.js

Closes #1998 
There's a reported issue where the Account Blocked modal displays briefly when navigating the site.  I haven't yet been able to reproduce this, but currently this modal always renders (and is just hidden with CSS).  This PR is an optimization to prevent the modal from rendering at all.  It will hopefully resolve the issue, but it will also reduce the size of the prerendered HTML.

fix: do not render account blocked modal unless account restricted

---

packages/api/src/pins.js
packages/api/src/utils/psa.js
packages/api/test/pin.spec.js
packages/api/test/user.spec.js
packages/db/index.js

resolves #1579 
What fixes are part of this PR: 
- ** I've created a [ticket](https://github.com/ipfs-shipyard/pinning-service-compliance/issues/245) in the compliance tool to discuss how the `status` query param should behave, since it is slightly confusing at the moment. You can find more context there, but for now I updated the apis in order to stick with what's expected by the compliance tool.
- [Delegates](https://github.com/ipfs-shipyard/pinning-service-compliance/blob/dbd8adcbb410579845dcbb584f097b3f74848c54/api.web3.storage.md?plain=1#L219) Created a separate [ticket](https://github.com/web3-storage/web3.storage/issues/2092) for this one. Might be worth waiting for picup migration to tackle this one 
- [Request with no authentication …

fix: PSA compliance fixes

---

.github/workflows/website.yml
package-lock.json
packages/website/next.config.js
packages/website/package.json
packages/website/tests/accountPayment.e2e.spec.ts
packages/website/tests/homepage.e2e.spec.ts
packages/website/tests/playwright/globalSetup.ts

A story in two parts…
This PR was started to fix an error with `playwright install-deps` which is showing up here: https://github.com/web3-storage/web3.storage/actions/runs/3620217854/jobs/6124601471
It seems that the dependencies which are required by the version of Playwright that we were using are no longer available on `ubuntu-latest` because `ubuntu-latest` is now a newer version. When that changed, this broke (is my educated guess). There are vague clues pointing at this being the case in this issue: https://github.com/microsoft/playwright/issues/19234
Bumping the playwright version seems to fix it. So that's the first part of this PR.
But fixing that made the Playwright tests run again. Which then uncovered another problem…
The `test-e2e` step in `.github/workflows/website.yml` was …

fix: bump 'playwright' version & fix intermittent e2e test failure

---

packages/website/pages/docs/how-tos/pinning-services-api.md

related to #2154 
This PR specifically covers updating the [docs](https://web3.storage/docs/how-tos/pinning-services-api/) part.

fix: update docs for PSA with IPLD codec info

---

.github/workflows/website.yml
packages/website/package.json
packages/website/public/.well-known/.gitignore
packages/website/scripts/did-document.ts

Motivation:
* this json file is the did doc when `did:web:{domain}` is resolved https://w3c-ccg.github.io/did-method-web/#read-resolve
* the did document sets `alsoKnownAs` to the did key
* add this simple did doc, just to make sure we can resolvce it via https://dev.uniresolver.io/
* once it resolves, we can iterate on exactly what's in the did doc

feat: website has /.well-known/did.json so did:web can resolve in prod

---

packages/website/components/contexts/tabGroupChoiceContext.js
packages/website/components/general/appProviders.js
packages/website/components/tabs/tabs.js
packages/website/lib/utils.js
packages/website/pages/docs/intro.md

I was working on the quickstart stuff for w3up and found myself really wishing that I had synchronized tab groups, so I can split the quickstart into broad categories (install, create space, upload, view, etc) and have the details in tabs for the various runtime envs (CLI, node, browser).
That would feel super awkward with our current non-syncing tabs, but I think it could be pretty cool if we get the tabs in sync.
Since I was having a bit of the old docs writer's block, I decided to just do it and ported over the feature from docusaurus, which is where I originally cribbed the tabs component in the first place.
There are a few minor changes from their implementation, mostly just using `@next/router` instead of their thing and using jsdoc for types instead of proper typescript.
There was …

feat: add synchronized, persistent tab groups

---

packages/db/postgres/functions.sql
packages/db/postgres/migrations/032-fix-add-pin-sync-req-for-pinned-items.sql

`create_content` stopped creating pin sync requests because it started using linkdex. This adds a new function `create_content_with_pin_sync_request` that does the same as `create_content` but also creates a pin sync request.
See https://github.com/web3-storage/web3.storage/commit/eae75d2366d59b0cf16143723a5af6513d891f9e#diff-bf4100e6931ed75d8fbe33d506c141af632f120f4df66bfd0ff9c92d80da40c6
Needa a followup to add items pinned after that PR to the sync list.

fix: add pin sync req for pinned items

---

packages/api/wrangler.toml

Update `CLUSTER_API_URL` in wrangler.toml to have the api use pickup in place of cluster for handling pinning service requests.
The prod pickup is currently configured to proxy all requests back over to cluster. The plan is to get pickup in the loop so we can control what fraction of requests it should handle from pickyup config.
Note: Merging this PR will trigger a staging deployment, which will apply the change to the staging config. Merging the release-please PR will trigger a prod deploy and the prod config change will be applied then.
TODO
License: MIT

feat: use pickup as `CLUSTER_API_URL`

---

.github/workflows/cron-pins.yml
packages/cron/test/email.spec.js
packages/cron/test/pins.spec.js

Change cron-pins ci workflow to use staging pickup for the staging run and prod for prod.
- uses `includes` to add `pickup_url` per env. see: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
- we can't use github environments here as you can only have 1 of those set on the job, you can't use them in a matrix.
Previously we used the same cluster url for both. We now want to see staging traffic hitting staging pickup.
Also cleans out some unused old cluster vars.
License: MIT

chore: use staging pickup in staging cron-pins job

---

packages/api/src/utils/billing-types.ts
packages/api/src/utils/number.js
packages/api/src/utils/stripe.js
packages/website/components/account/currentBillingPlanCard/currentBillingPlanCard.js
packages/website/components/account/paymentTable.js/paymentTable.js
packages/website/components/account/storageManager/storageManager.js
packages/website/components/accountPlansModal/accountPlansModal.js
packages/website/components/contexts/plansContext.js
packages/website/hooks/use-payment.js
packages/website/lib/utils.js
packages/website/pages/account/index.scss
packages/website/pages/account/payment.js

This continues to only allow the _selection_ of a standard plan, but if a user is associated with a non-standard plan in Stripe we will now return this data (specifically tier information and metadata) to the UI in order to populate custom cards.  This will be necessary as we migrate early adopters to custom plans as well as for custom plan functionality in general.
This also includes an API change to ensure that all of our users have at least a subscription to the Free tier.  We want to migrate away from modeling early adopters as users without a subscription and instead explicitly put them into a tier.
Update UIs
See [here](https://www.notion.so/UIs-for-custom-plans-post-migration-df237239d19049e999e2284478ed372d)

feat: allow displaying of custom stripe prices

---

packages/api/src/pins.js

When using kubo to `ipfs remote pin add` we get a GET request every second checking for an update to the pin status.
Here we use that as a trigger to ask pickup for a status update. This will be handled by a lambda invocation and a single item db read, and will be pretty low impact.
In return we will be able to inform the user as soon as their pin is complete rather than having to wait up to an hour for an async pin update job to complete.
fixes https://github.com/web3-storage/web3.storage/issues/2213
License: MIT

feat: recheck pin status on GET /pins/:req-id

---

packages/website/components/contexts/plansContext.js

closes #2205 
Note that this *only* changes the price information in the UI.  Before we begin sending usage information to Stripe for calculating overages we'll need to migrate users from their current prices to ones that match pricing structure of the ones we're displaying in the UI. (Stripe prices are immutable and so it appears this migration is necessary.)

fix: update price displayed in UI to reflect advertised price

---

packages/api/src/car.js

Include the R2 key in the error message for better visibility when debugging.
We're getting rate limits for put with the same key...

fix: include key in error message

---

packages/website/components/contexts/plansContext.js

fix: remove '/mo' from free tier description

---

packages/client/src/lib.js
packages/client/test/put.spec.js

Per talk async with @alanshaw , setting default chunk size to 50MB to save us 5x in number of indexes needed to write/read R2

fix: set client default chunk size to 50MB

---

package-lock.json
packages/w3/package.json

To start using the 50MB chunk size.
Thank you to @hammertoe for the nudge. This was overlooked when we made the change to the client lib, and increase the max size of files we can serve through freeway.
License: MIT

feat: update to latest web3.storage@4.5

---

packages/website/pages/_app.js

The Simple Analytics event handlers being attached to all of our links is interpreting the path `/docs` as a link to a download and blocking the default action of this event.  It appears this is because it's mistaking this path as a link to a .doc file.  Explicitly setting the file extensions to their defaults but removing the `doc` extension seems to fix this.  Probably a bad regex on their end.
See #2237

fix: apply workaround to Simple Analytics blocking navigation to /docs

---

packages/api/src/user.js
packages/api/src/utils/billing-types.ts
packages/api/src/utils/billing.js
packages/api/src/utils/stripe.js
packages/api/test/user.spec.js

Fixes #2225 
This eliminates a race condition causing the creation of multiple customers in Stripe.  New customers are now treated as if they're in the free tier without actually giving them a stripe customer.

fix: stop creating a Stripe account during web3.storage account creation

---

package-lock.json
packages/api/package.json
packages/api/src/car.js
packages/api/test/car.spec.js

Use new lib to validate blocks https://github.com/web3-storage/car-block-validator so that we can support all the hashers. Alternatively, we can block on linkdex `getDagStructure` which currently is done in `waitUntil`.
Thoughts?

fix: use car block validator

---

packages/api/src/pins.js
packages/api/src/utils/pin.js
packages/db/db-client-types.ts

Update pin status for pins regardless of status. Previously we only updated if the state was positive.
Pickup will not retry pins that timeout, so the change here ensures we inform users promptly where that happens.
Where the user has a pending pin, the request will now synchronously go check cluster/pickup, update the db and return the response. Previously the worker would respond early, and poll for a positive pin status from the upstream for up to 30s. Just checking the upstream once per request seems sufficient. We may want to rate limit this end point in the future, but it's pretty low volume currently.
fixes #2234 
License: MIT

fix: update pin status from GET /pins even if failed

---

packages/api/src/car.js

there are a few entries in DUDEWHERE bucket with CIDv0. Example: https://dash.cloudflare.com/fffa4b4363a7e5250af8357087263b3a/r2/default/buckets/dudewhere-prod-0
This won't work with reading from freeway from w3s.link when we always redirect to CIDv1

fix: dudewhere root cid should be content cid

---

.github/workflows/website.yml
package-lock.json
packages/api/package.json
packages/api/src/car.js
packages/api/src/env.js
packages/api/src/utils/bucket.js
packages/api/test/scripts/worker-globals.js
packages/api/wrangler.toml

If linkdex says the DAG is complete, then ask gendex to generate block indexes for each block in the DAG.
This is done by sending a message to a cloudflare queue.
There's a queue consumer worker ([gendex-consumer](https://github.com/web3-storage/gendex-consumer)) that calls [gendex](https://github.com/web3-storage/gendex) to get block indexes generated.

feat: trigger block index creation

---

.github/workflows/website.yml

These are currently failing as magic.link is failing to successfully log users in using the special test email `test+success@magic.link` (https://magic.link/docs/auth/introduction/test-mode#usage):

fix: temporarily disable e2e tests

---

packages/api/wrangler.toml

Getting error when deploying to staging/production:
```
The compatibility flag streams_enable_constructors became the default as of 2022-11-30 so does not need to be specified anymore.
The compatibility flag transformstream_enable_standard_constructor became the default as of 2022-11-30 so does not need to be specified anymore.
[code: 10021]
```

fix: remove unnecessary compatibility flags

---

packages/api/wrangler.toml

Fix to use the staging gateway from the staging api
License: MIT

fix: use dag-staging gateway from staging api

---

.github/workflows/website.yml
package-lock.json
packages/website/components/messagebanner/messagebanner.scss
packages/website/components/page-banner/page-banner-portal.js
packages/website/components/w3up-launch.js
packages/website/modules/docs-theme/index.js
packages/website/pages/_app.js
packages/website/pages/_document.js
packages/website/pages/account/index.js
packages/website/pages/account/payment.js
packages/website/pages/index.js

Motivation:
* https://github.com/web3-storage/secrets/issues/20
Tactics:
* there is a new env var `NEXT_PUBLIC_W3UP_LAUNCH_SUNSET_ANNOUNCEMENT_START` that is an ISO8601 datetime of when the announcement should appear. If unset, the announcement will never appear. My intention is to set it only on the staging environment for acceptance testing. Once we're happy on staging, we can enable it on production by setting this var to whatever datetime we want it to appear.
Scope:
* when enabled at after the appropriate time, the banner should appear on the following routes
* /
* /account
* /account/payment
* /docs
* the github actions `website` workflow now uses github environments. This is because I want to use them to configure the staging environment to have a particular value for …

feat: add w3up-launch announcement banner (when env.NEXT_PUBLIC_W3UP_LAUNCH_SUNSET_ANNOUNCEMENT_START is set)

---

packages/website/content/pages/index.json

Motivation:
* https://github.com/web3-storage/secrets/issues/26

feat: remove 'whats the data layer?' cta2 from website homepage

---

packages/client/package.json

Needed for newer typescript with certain moduleResolution settings.
Found the explanation & solution here:
https://github.com/gxmari007/vite-plugin-eslint/pull/60
& the docs for the option here:
https://nodejs.org/api/packages.html#packages_exports (with `types` being defined here: https://nodejs.org/api/packages.html#conditional-exports)

fix: add types to package.json exports

---

.github/workflows/api.yml
packages/api/test/user.spec.js

…vars so that the env vars like NEXT_PUBLIC_W3UP_LAUNCH_ get added to cf worker vars
Motivation:
* https://github.com/web3-storage/web3.storage/issues/2327
* tldr fix so that gh env vars get released with packages/api to staging/production environments on cloudflare

ci: .github/workflows/api.yml when using wrangler-action passes with vars

---

.github/workflows/api.yml

Motivation:
* i want to use `vars` for https://github.com/web3-storage/web3.storage/pull/2328 but it didn't work due to old wrangler action

ci: api.yml upgrade wrangler-action to 3.3.2 to use vars var

---

packages/api/src/auth.js
packages/api/src/env.js
packages/api/src/maintenance.js
packages/api/test/maintenance.spec.js

We are currently running a verification job to get report of what in `dotstorage-prod-1/raw/*` still needs to be migrated. It has been running for 10 days and looks like it will still take some time until finishing.
We want to rely on maintenance mode to disable writes, so adding a way to bypass maintenance mode for list of allowed tokens, so that we can still write the report when done for this bucket.
TODO:

feat: bypass maintenance mode for allowed tokens

---

.github/workflows/api.yml

...to be resilient to staging writes being disabled
Motivation:
* this pipeline after merging a release-please PR failed the deploy to staging job and I think this change would make it green. https://github.com/web3-storage/web3.storage/actions/runs/7616473142

ci: .github/workflows/api.yml test upload to staging step using api-staging.web3.storage now has continue-on-error: true 

---

packages/website/pages/pricing.js

You can no longer pay for storage with the legacy API.

fix: hide pricing info

---

packages/db/index.js
packages/db/postgres/pg-rest-api-types.d.ts
packages/db/postgres/tables.sql
packages/db/test/upload.spec.js
packages/db/utils.js

Motivation:
* add support for backup urls from backup table to https://github.com/web3-storage/web3.storage/pull/2347

feat: list uploads joins to backup table to get backup urls

---

package-lock.json
packages/api/package.json
packages/cron/package.json
packages/db/package.json

Motivation:
* I want to release the db change from here https://github.com/web3-storage/web3.storage/pull/2352 in a way that the api also gets released and making use of it
* When I merged that last PR, there was no release-please PR generated for api. iiuc, that's because the PR only touched the db package, but not the api package (that depends on db)
* hoping that this change that touches the api package.json will release things as desired

feat: bump db package to 4.1.0 and use dep on that new version from cron, api packages

---

packages/api/src/index.js

Re-enable creating API tokens
Currently the whole API is in read only mode. This allows tokens to be created and deleted by moving the handler outside the read/write mode protections

fix(api): re-enable tokens endpoints outside read-write
