- packages/api/wrangler.toml
Hey, I just followed along with the README instructions to spin up a dev api, and things seem to work :)
The README told me to open a PR, so here you go 😄
> add env.yusef to wrangler config

- README.md
- package-lock.json
- package.json
- packages/api/README.md
- packages/api/package.json
- packages/api/test/cors.spec.js
- packages/api/wrangler.toml
- packages/client/README.md
- packages/client/package-lock.json
- packages/client/package.json
- packages/client/src/lib.js
- packages/client/test/get.spec.js
- packages/client/test/interface.spec.js
- packages/client/test/store.spec.js
> chore: web3.storage all teh thingz! 🚀✨🌙

- package-lock.json
- packages/client/package.json
- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/client/test/put.spec.js
We know the cid once the car is generated from the given files. We can give them to the user already, as this will allow use cases of parallel processing data.
This PR adds a function option, similar to the provided for tracking upload progress that a user can rely
> feat: onRootCidReady

- package-lock.json
- package.json
- packages/w3/bin.js
- packages/w3/index.js
- packages/w3/package-lock.json
- packages/w3/package.json
- get things from web3!!1!
```
w3 --get bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu --output pics --api http://127.0.0.1:8787
```
This is very much a demo at this point, and tbc, but useful for testing things.
> feat: add `w3` cli

- packages/client/README.md
- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
Update the dreamcode to show where we're almost at.
> docs: update usage in client readme

- packages/api/pw-test.config.cjs
- packages/api/src/index.js
- packages/api/test/scripts/node-globals.js
Fixes the tests - some test code in src until playwright is fixed cc @hugomrdias
> fix: tests

- packages/db/fauna/schema.graphql
As per https://protocollabs.slack.com/archives/C01MPC37Z37/p1625566796236500
> fix: chainDealId should be unique

- packages/api/src/car.js
just mutate the cloned response headers instead, otherwise you can hit "Can't modify immutable headers." errors, which i started seeing on the staging deployment.
see: https://developers.cloudflare.com/workers/examples/alter-headers
> fix: Don't mutate immutable Headers object

- README.md
- packages/api/src/index.js
- packages/website/components/navbar.js
> In observational astronomy, an asterism is a popularly-known pattern or group of stars that can be seen in the night sky. This colloquial definition[a] makes it appear quite similar to a constellation,[1] but they differ in that a constellation is a formally-named area of the sky and all the celestial objects within it, representing an object, person, or animal, often mythological; while an asterism is a visually obvious collection of stars and the lines used to mentally connect them. As such, asterisms do not have officially determined boundaries and are therefore a more general concept which may refer to any identified pattern of stars.
– https://en.wikipedia.org/wiki/Asterism_%28astronomy%29
> a typographic symbol consisting of three asterisks placed in a triangle, and is a type of …
> nice: asterism ⁂

- .github/workflows/website.yml
- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/website/components/hero.js
- packages/website/pages/files.js
- packages/website/pages/tokens.js
- pin to our cluster from ci when PR merged to main
- minimal fixes to site and client to make test and build ok
> chore: deploy staging website from CI

- .github/workflows/website.yml
> chore: fix website staging deploy

- .github/workflows/website.yml
- package-lock.json
- packages/website/next.config.js
- packages/website/package.json
- skip eslint in build (for now)
- build website in ci and fix path to output
> chore: fix website build and ci deploy

- package-lock.json
- packages/api/src/index.js
- packages/api/src/user.js
- packages/api/test/mocks/db/post_graphql.js
- packages/api/test/user.spec.js
- packages/db/fauna/resources/Function/deleteUserUpload.js
- packages/db/fauna/schema.graphql
- packages/website/lib/api.js
- packages/website/pages/files.js
Adds DELETE /user/uploads/:id to API and wires it up in UI
Given we are going with DELETE /user/uploads/:id I didn't add a delete to the client, as this is not a /car route. Happy to add it as well
All flow tested with local setup from website
> feat: delete user upload

- packages/client/README.md
- add banner
- update the getting started now we've published
- add intro para to example
> docs: update client README

- packages/api/test/car.spec.js
> chore: api car test expects cid from car to be returned

- .github/workflows/api.yml
- packages/api/package.json
- packages/api/webpack.config.js
- Add api bundlesize check
- minify bundle
fixes #79 (hopefully)
> chore: add api bundlesize check

- packages/api/src/index.js
- packages/api/src/user.js
- packages/api/test/user.spec.js
- packages/db/fauna/resources/Function/deleteUserUpload.js
- packages/db/fauna/schema.graphql
- packages/website/lib/api.js
- packages/website/pages/files.js
> fix: delete upload by cid

- packages/website/components/button.js
- packages/website/components/modal.js
- packages/website/content/file-a-request.json
- packages/website/package-lock.json
- packages/website/package.json
- packages/website/pages/_document.js
- packages/website/pages/login.js
- packages/website/pages/profile.js
- Adds the profile page structure
- Adds a json with the "file a request" email template
- Adds a `Modal` component
- Changes the login to redirect to the profile page
------
https://user-images.githubusercontent.com/34691925/125676600-2bd74e5c-db82-49d8-be6a-c639544a3b02.mov
> feat: add profile page

- package-lock.json
- packages/client/package.json
- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/client/test/fixtures/status.json
- packages/client/test/mocks/api/get_status#@cid.js
- packages/client/test/status.spec.js
- fetch the /status/:cid data for a given cid
- return undefined on 404... like asking a Map for a key it doesn't have
- throw on server error
> feat: client.status(cid)

- packages/api/wrangler.toml
> chore: add rafaelramalho to wrangler.toml

- packages/client/src/lib/interface.ts
Nice TS docs to help developers.
> docs: type docs

- package-lock.json
- packages/api/src/status.js
- packages/api/test/fixtures/find-content-by-cid-no-aggregate.json
- packages/api/test/fixtures/find-content-by-cid-no-deal.json
- packages/api/test/fixtures/find-content-by-cid.json
- packages/api/test/mocks/db/post_graphql.js
- packages/api/test/status.spec.js
- packages/db/README.md
- packages/db/fauna/resources/Function/addAggregateEntries.js
- packages/db/fauna/resources/Function/createAggregate.js
- packages/db/fauna/resources/Function/createOrUpdateDeal.js
- packages/db/fauna/resources/Function/createOrUpdatePin.js
- packages/db/fauna/resources/Index/aggregateEntryByAggregateAndContent.js
- packages/db/fauna/schema.graphql
- packages/website/content/about.md
resolves #83
I have also added a `created` date to `Pin`.
> refactor: renames

- packages/website/content/about.md
- packages/website/pages/about.js
- Disables any interaction with the illustration so the text is always on top
- Adds small fixes to the markdown file
> fix(about): disable illustration interaction

- packages/db/fauna/resources/Function/addAggregateEntries.js
If DAG size of each entry is sent as part of a call to `addAggregateEntries` and the `Content` the entry refers to does not yet have a `dagSize` set then set it.
This allows us to avoid having a separate cron job for obtaining the size of BIG DAGs since this information is sent from the Storage Broker.
> feat: update Content dagSize from addAggregateEntries

- package-lock.json
- packages/w3/package.json
> chore: ensure w3 has dep on web3.storage

- .github/workflows/release.yml
- add db and website deploy steps
- add PROD_FAUNA_KEY to secrets
> chore: add prod release ci config

- package-lock.json
- packages/api/package.json
- packages/cron/src/jobs/pins.js
> refactor: change API module name

- packages/api/src/user.js
- packages/website/components/button.js
- packages/website/components/checkbox.js
- packages/website/icons/tick.js
- packages/website/pages/files.js
- packages/website/tailwind.config.js
- packages/website/utils/adapters/files.js
selected row: 
- The export deals is not ready in the backend
- The size information
- Pagination
> feat: style files page

- package-lock.json
- packages/api/package-lock.json
- packages/website/components/button.js
- packages/website/package.json
- packages/website/pages/new-token.js
- packages/website/pages/profile.js
- packages/website/pages/tokens.js
- packages/website/tailwind.config.js
Thanks @rafaelramalho19 for the table styles 😉
> style: api token management pages

- package-lock.json
- packages/client/package.json
- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/client/test/put.spec.js
- packages/w3/README.md
- packages/w3/bin.js
- packages/w3/index.js
- packages/w3/test/e2e.spec.js
- add `wrapWithDirectory` option to client
- add `--no-wrap` flag to `w3
- add tests
> feat: user option for wrapWithDirectory

- packages/website/components/checkbox.js
- packages/website/pages/files.js
Fixed all issues referenced in https://github.com/web3-storage/web3.storage/pull/106#issuecomment-885551786
> Feat: files pagination & bug fixes

- packages/website/components/layout.js
- packages/website/components/navbar.js
- packages/website/components/types.d.ts
- packages/website/lib/user.js
Fixing the user loading states so we don't show a login button before we determine if the user is logged in.
> fix: user loading states

- packages/website/components/button.js
- packages/website/components/hero.js
- packages/website/components/navbar.js
- packages/website/lib/user.js
- packages/website/pages/index.js
> fix: mobile styles

- packages/website/components/checkbox.js
- packages/website/pages/files.js
Fixes: 
-  Files timestamp has different formats
- Files page's checkboxes were not keyboard accessible
> chore: files page ui tweaks

- packages/website/pages/new-token.js
- packages/website/pages/tokens.js
- Fixes "no tokens" page style
- Fixes "create token" placeholder text
> Chore/improve tokens UI

- packages/website/content/about.md
- packages/website/package-lock.json
- packages/website/package.json
- packages/website/pages/about.js
- Adds link capabilities to every heading in the about page
> chore: add links to the headings on the about page

- packages/website/pages/files.js
> chore: improve files page empty state

- packages/website/components/hero.js
- packages/website/pages/callback.js
- packages/website/pages/index.js
- packages/website/tailwind.config.js
- Users who log-in now get landed on the Profile tab
- Copy edit changes on the hero asset to better land our message.
- Changed background color of the "Decentralized Storage in... " + Code snippet section
- Edited copy to the paragraph under "Getting Started on Web3.Storage"
Closes https://github.com/web3-storage/web3.storage/issues/169
> chore: apply ui feedback to the homepage

- packages/website/components/hero.js
Fixes https://github.com/web3-storage/web3.storage/issues/154
> chore: fix cliping in homepage

- package-lock.json
- packages/website/package-lock.json
- packages/website/package.json
> chore: update web3.storage dep

- packages/website/components/tooltip.js
- packages/website/icons/copy.js
- packages/website/package-lock.json
- packages/website/package.json
- packages/website/pages/files.js
- packages/website/pages/index.js
- packages/website/pages/upload.js
- packages/website/styles/global.css
- Tweak how drag and drop works to enable a larger area for files to be dropped and fix the rapid flashing
- Copy CID button next to the CID to make it easier for users to grab relevant CIDs.
- Including link to Column definitions
- Rename "Upload Files" button to "Upload More Files" (when we already have files, otherwise it's called Upload Files)
- Make the default width of the table (even when empty) wider to minimize how much the table flexes in size. 
- Visually increase the size of the drag and drop area
> Files UI Feedback 

- packages/website/content/about.md
- packages/website/styles/global.css
Fixes. https://github.com/web3-storage/web3.storage/issues/182
> chore: change about page's copy

- packages/website/pages/_app.js
- packages/website/pages/files.js
- Disables refetch on windows focus
- Adds a button to refresh the files page
> chore: query changes

- .github/workflows/api.yml
- .github/workflows/release.yml
- package-lock.json
- packages/api/package.json
- packages/api/src/env.js
- packages/api/webpack.config.js
Adds webpack plugin to add source maps for sentry usage
- Secrets were added to the repo
TODO:
```
Reason | invalid character '/'
-- | --
Value | @web3-storage/api-1.0.1
```
NOTE: This needs to be tested in staging/production to guarantee everything is as expected
> fix: sentry source maps

- .github/workflows/release.yml
one small tweak for me. one giant leap for webkind.
> chore: update dnslink domain to _dnslink

- packages/website/components/navbar.js
- packages/website/content/about.md
- packages/website/pages/account.js
- packages/website/pages/callback.js
- packages/website/pages/login.js
- Renames profile page to `account`
- Changes all links to /account
cc @terichadbourne for docs changes
> chore: rename profile page to account

- packages/website/pages/login.js
> chore: re-order login options

- packages/website/components/checkbox.js
- packages/website/pages/files.js
- Disables the checkbox when a file is still being uploaded
> chore: stop file deletion when its still uploading

- packages/website/components/hero/hero.js
- Adds paddings to the hero text so it doesn't reach the edges
> chore: fix hero paddings

- package-lock.json
- packages/website/components/button.js
- packages/website/components/footer.js
- packages/website/components/hero/hero.js
- packages/website/components/navbar.js
- packages/website/lib/countly.js
- packages/website/lib/types.d.ts
- packages/website/next.config.js
- packages/website/package.json
- packages/website/pages/404.js
- packages/website/pages/_app.js
- packages/website/pages/_document.js
- packages/website/pages/account.js
- packages/website/pages/files.js
- packages/website/pages/index.js
- packages/website/pages/login.js
- packages/website/pages/new-token.js
- packages/website/pages/tokens.js
- packages/website/pages/upload.js
Creating this PR for visibility of the work in progress.
- Simple 404 page added for this
- `NEXT_PUBLIC_COUNTLY_KEY`
- `NEXT_PUBLIC_COUNTLY_URL`
(Requirements [here](https://www.notion.so/protocollabs/storage-metrics-ee4ec19916e440e1aa3e3b0f2cc7030b#16d5bacaacd7431a8fc2caa1052fd372)).
> chore: add countly analytics integration for user tracking

- package-lock.json
- packages/report/bin.js
- packages/report/index.js
- packages/report/package.json
Allows to save all data in the report to CSV for querying.
> feat: save report to CSV

- package-lock.json
- packages/api/package.json
- packages/cron/package.json
We think this will fix a sproadic error we are seeing adding CARs to cluster in web3.storage.
> fix: set stream-channels=false for cluster add

- packages/w3/bin.js
- packages/w3/index.js
- feat: Add --name flag to w3 put
- feat: Add --hidden flag to w3 put
resolves #316
> put name hidden

- packages/website/components/navbar.js
- packages/website/styles/global.css
> fix: logo text style

- packages/website/pages/account.js
> chore: update storage copy for the account page

- package-lock.json
- packages/api/src/user.js
- packages/api/test/fixtures/get-user-uploads/find-uploads-by-user-sorted-by-name.json
- packages/api/test/mocks/db/post_graphql.js
- packages/api/test/user.spec.js
- packages/db/fauna/resources/Function/findUploadsByUser.js
- packages/db/fauna/resources/Index/uploadByUserSortByCreatedAsc.js
- packages/db/fauna/resources/Index/uploadByUserSortByNameAsc.js
- packages/db/fauna/resources/Index/uploadByUserSortByNameDesc.js
- packages/db/fauna/schema.graphql
This PR adds support for sortBy and sortOrder in the API and DB Function. 
The support for PinStatus and Size needs to be added as a follow up, as there are a few open questions that we should move to an issue:  https://github.com/web3-storage/web3.storage/pull/379#discussion_r693995972
Meanwhile, we can unblock UI work with these
Query Example in fauna Dashbord (needs to have userId updated to a valid one for you):
```
query findUploadsByUser {
findUploadsByUser (where:{ user: "303388817558077963", createdBefore: "2021-09-09T19:07:16.161Z"}, sortBy: Name, sortOrder: Asc, _size: 10) {
data {
_id
name
content {
cid
dagSize
}
created
}
}
}
```
> feat: api supports upload list sorting

- package-lock.json
- packages/client/package.json
With fix from https://github.com/web3-storage/files-from-path/pull/8
> fix: update files from path dep with types fixed

- packages/api/src/index.js
- packages/api/src/user.js
- packages/db/fauna/resources/Function/renameUserUpload.js
- packages/db/fauna/schema.graphql
- packages/website/components/loading.js
- packages/website/icons/pencil.js
- packages/website/icons/spinner.js
- packages/website/lib/api.js
- packages/website/pages/files.js
Closes https://github.com/web3-storage/web3.storage/issues/416
- This PR allows for awesome and quick edit of a upload's name 🎉 
https://user-images.githubusercontent.com/24696635/131395673-88d5eb45-64e7-4ec7-b6d1-518e817a72f9.mov
> feat: allow uploads to be renamed

- packages/website/pages/tokens.js
Closes https://github.com/web3-storage/web3.storage/issues/433
> fix: button size on the tokens page

- packages/website/pages/files.js
> fix: make refresh fetch recent uploads

- packages/website/components/button.js
- packages/website/components/footer.js
- packages/website/pages/files.js
- Improves the table inside the files page (with nowrap):
- Improves the buttons behavior on top of the table:
https://user-images.githubusercontent.com/34691925/132368917-c918a5e1-c1ee-4f7e-9af2-dd9db405dc4f.mov
- Adds some minor accessibility improvements
Closes #430
Closes #431
> fix: improve table layout inside files page

- packages/website/components/footer.js
Changes the "Made with..." text to be the same font size as the other links
Closes #432
> fix: use the same font size for the whole footer

- .github/workflows/cron-test.yml
everything works *except* the run duration metric value is not appering in prom.
> chore: debug missing upload metric

- packages/website/pages/tokens.js
- Shortens the token and prevents it from wrapping
- Improves the table responsiveness
Closes #455
> feat: improve tokens table

- packages/db/postgres/cargo.sql
- packages/db/postgres/tables.sql
This PR adds the postgres schema based on:
- https://github.com/web3-storage/web3-schema/blob/main/schema.sql
- https://github.com/web3-storage/web3.storage/blob/main/packages/db/fauna/schema.graphq
- https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/api/db/tables.sql
> feat: postgres schema

- package-lock.json
- packages/api/package.json
- packages/api/src/env.js
- packages/api/webpack.config.js
- packages/api/wrangler.toml
- delete the source map after it has been sent to sentry but before it would be uploaded to cloudflare
- skip building a sourece map in dev
- skip the extracting comments to a license file
builds on #505
may help with #499
> chore: dont send source-map to cloudflare

- package-lock.json
- packages/website/pages/files.js
- Adds a tooltip to the pin status with useful information 
Closes #429
> feat: add tooltip to the pin status

- packages/cron/src/jobs/metrics.js
Add cid number tracking to ease migration analysis
> feat: add count cids

- packages/db/postgres/client.js
- packages/db/postgres/functions.sql
- packages/db/postgres/tables.sql
They were removed to ease migration of data in previous PR https://github.com/web3-storage/web3.storage/pull/580
> fix: re-add constraints

- packages/api/wrangler.toml
- Updated wrangler.toml with my personal development environment.
- Update wrangler template comment to include PG link.
> Setting up Cloudfare env for myself

- packages/cron/src/lib/utils.js
- packages/db/postgres/client.js
Pin sync request query should ask id as text as well
> fix: pin sync req id text

- packages/website/components/button.js
- packages/website/components/navbar.js
- packages/website/pages/files.js
- Adds a user survey to the `/files` page
- Fixes spacing issues in the navbar
Closes #463 
Closes #556
> feat: add user survey

- packages/website/content/about.md
> docs: change advertised max file limit to 31GiB

- .github/workflows/cron-dagcargo-views.yml
Adds cron workflow for dagcargo refresh views (secrets also added)
> feat: workflow dagcargo refresh views

- packages/client/src/lib.js
- Improves the listing upload error handling, adding the error message from the API:
> chore: improve error message when listing uploads

- packages/website/components/layout.js
- packages/website/next.config.js
This PR adds api version and commit to website meta tags
Closes #448
> feat: add website version and commit to meta tags

- packages/api/src/index.js
- packages/api/src/pins.js
- packages/api/src/utils/json-response.js
- packages/api/test/pin.spec.js
Adds endpoints:
- POST /pins
- GET /pins/:requestId
- GET /pins
- DELETE /pins/:requestId
Adds payload validation and tests
> Add skeleton for pinning API endpoints

- packages/website/components/alert.js
- packages/website/components/navbar.js
- packages/website/icons/cross.js
- packages/website/pages/upload.js
- packages/website/styles/global.css
closes https://github.com/web3-storage/web3.storage/issues/278
> feat: handle upload errors

- packages/api/test/mocks/pgrest/post_rpc#find_deals_by_content_cids.js
- packages/api/test/status.spec.js
- packages/db/index.js
- packages/db/utils.js
A regression from the DB migration.
See definition here:
https://github.com/web3-storage/web3.storage/blob/b865bfbf919f084792b49df4e580ec3339e55778/packages/client/src/lib/interface.ts#L202-L205
...and old definition here:
https://github.com/web3-storage/web3.storage/blob/2f9c86a5c33f8f701360c531e2915fe82b9753b1/packages/db/fauna/schema.graphql#L306-L313
> fix: data CID is root CID of aggregate, not content CID

- packages/api/src/index.js
Temporary backdoor bypassing maintenance mode middleware
> feat: temporary api backdoor

- packages/website/components/layout.js
- packages/website/components/loading.js
- packages/website/components/navbar.js
- packages/website/styles/global.css
Fixes #703  navigation links, there where some other consistency updates:
- Navigation Links are handled by nextjs router/link component
- Styles for navbar made consistent during loading so it's not flashing white
- Added the maintenance banner to loading so the navigation bar doesn't move when loading
- Updated page background color to be consistent with navbar color during loading screen
> Issue 703 - Navigation Links the Nextjs way

- packages/website/pages/files.js
fixes #689 adds new availability column and pin tooltip message
> feat: issue 689 added new column and metadata for review

- packages/website/pages/files.js
> fix: mispelled available

- packages/website/components/account/storageManager/storageManager.scss
- packages/website/components/account/storageManager/storageManager.tsx
---
- Moving storage meter section sizes into code for referencing and calculations
- Updating bar growth logic for proportionate sizing based off of the width of each section and their storage alottment
> refactor: Proportionate sizing based off of usage and sections

- packages/api/src/car.js
Closes https://github.com/web3-storage/web3.storage/issues/761
> fix: add metadata to backup

- packages/website/components/button/button.scss
- Fixing lost font weights around buttons
> fix: Fixing weird button font weights

- packages/website/components/account/filesManager/fileRowItem.js
- packages/website/components/footer/footer.js
- packages/website/components/tokens/tokensManager/tokensManager.js
> hotfix: cleaning up logs

- packages/website/components/breadcrumbs/breadcrumbs.js
- packages/website/components/breadcrumbs/breadcrumbs.scss
- packages/website/components/navigation/navigation.js
- packages/website/components/navigation/navigation.scss
- packages/website/content/pages/general.json
- packages/website/styles/global.scss
Breadcrumbs component + styling added to navigation
> feat Marketing site breadcrumbs

- packages/website/.storybook/main.js
- packages/website/modules/zero/components/dropzone/dropzone.js
Added preliminary dropzone upload progress information
> feat Dropzone progress

- packages/api/src/metrics.js
- packages/api/test/metrics.spec.js
Graph also removed from grafana
Closes #833
> chore: remove commented metrics for dag size sum in pins

- packages/website/pages/about.js
- packages/website/pages/faq.js
- packages/website/pages/index.js
- packages/website/pages/terms.js
- packages/website/pages/tiers.js
- Adding static props to all marketing pages
> fix: Adding static props for exporting index file

- packages/db/index.js
- packages/db/test/pinning.spec.js
Bug: GET pins/ is listing deleted pin requests
> fix: unlist deleted pin requests

- packages/website/pages/tiers.scss
Quick fix for an issue where an invisible container was blocking the selection of some content on the Tiers page
> fix: Selection blocking container on Tiers page

- packages/api/src/pins.js
- packages/api/test/pin.spec.js
> Fix PSA pin statuses when unpinned

- .github/ISSUE_TEMPLATE/config.yml
- package-lock.json
Updated email copy as follows:
```
``` Please share the user authentication method (Github, Email) associated with your account ```
```Please share links (Github, website, etc) for what you're building. This is to help ensure the service is not being used in violation of our terms of service.``` 
```Any details around how and why your project would use the pinning services API would be helpful so we can verify that you will not abuse the service.```
```Please share 5-10 CIDs of content that you would be pinning.```
```
> fix: updated mailto link copy

- packages/api/wrangler.toml
I _think_ the top level durable objects config does not work when publishing for reals.
> fix: durable objects config

- packages/website/components/account/filesManager/fileRowItem.js
- packages/website/components/account/storageManager/storageManager.tsx
- packages/website/modules/zero/hooks/useQueryParams.js
- packages/website/pages/api/version.js
- Fixing superfluous html in name editing
- Fixing console error form missing local api route
- Hooking up "search my files" button
- Fixing searchbar filter issues where deleting the last item doesn't clear the filters
- Fixing persistent queries not working when visiting a url with query params
> fix: Misc app UI fixes

- packages/website/components/accordionblock/accordionblock.js
- packages/website/components/navigation/navigation.js
- packages/website/components/navigation/navigation.scss
- packages/website/modules/zero/components/accordion/accordion.js
Account dropdown added to the nav on the marketing site. Also a small issue was fixed with the accordion expand all option displaying in the nav account dropdown on mobile.
> feat: marketing site nav account dropdown

- packages/website/components/card/card.scss
- packages/website/components/footer/footer.scss
- packages/website/components/messagebanner/messagebanner.scss
- packages/website/components/navigation/navigation.scss
- packages/website/pages/about.scss
- packages/website/pages/index.scss
- packages/website/pages/tiers.scss
- packages/website/styles/global.scss
- packages/website/styles/variables.scss
Issues flagged in [this task](https://app.asana.com/0/0/1201717596388768/f) with text selection have been fixed. A new mixin called `gradient_Text_Selection` has been added and must be included on a parent of any gradient text element in order for the correct highlighting to appear when selecting it.
> fix: highlight selection tweaks

- packages/api/src/car.js
> fix: size for single block raw node

- packages/db/postgres/tables.sql
Porting over from NFT to support api token blocking in the admin site: https://github.com/nftstorage/nft.storage/pull/1203
> Feature #563: Schema updates for admin site.

- packages/website/components/button/button.scss
- packages/website/styles/variables.scss
Hover effects have been added for two buttons across the entire site (Marketing + App). Dark button types now have a blurred gradient outline on hover and animated gradient background on active. Pink-blue gradient buttons now have their gradients animated on hover.
> feat Button hover effects

- packages/db/postgres/tables.sql
see #955
Cousin pr in nft.storage https://github.com/nftstorage/nft.storage/pull/1378
> Addressing PR feedback for user_tag table to allow tag value type (see #955)

- packages/db/postgres/tables.sql
* Also adding a reason field on the user_tag table.
> Adding ACCOUNT_ENABLED user_tag_type to support blocking/unblocking a user

- packages/website/components/account/filesManager/fileRowItem.js
- packages/website/components/account/filesManager/filesManager.tsx
- packages/website/components/account/storageManager/storageManager.tsx
- packages/website/components/card/card.js
- packages/website/components/contexts/uploadsContext.js
- packages/website/components/contexts/userContext.js
- packages/website/components/imageblock/imageblock.js
- packages/website/content/pages/app/account.json
- packages/website/lib/api.js
- packages/website/pages/account/index.tsx
- Fixing type issues that prevented build
- Adding in `unoptimized` prop
- Hooking up name editing of files to `renameUpload` api
- new functionality to edit only 1 name at a time
- Save by clicking on the pencil icon again
- Hooking up `usedStorage` to actual API
> feat: Fixing type issues, hooking up functionality, minor bugs in new brand site

- packages/website/components/account/filesManager/fileRowItem.js
- packages/website/components/account/filesManager/filesManager.tsx
- packages/website/components/contexts/userContext.js
> fix: Type fixes

- PEERS
Adds the 3 new peers from cluster
> fix: peers list

- packages/db/postgres/tables.sql
nft.storage PR [here](https://github.com/nftstorage/nft.storage/pull/1397)
> Renaming user blocked and psa user_tags (closes #1002)

- packages/website/components/button/button.scss
- packages/website/next-env.d.ts
- packages/website/pages/tiers.scss
Hover/active effects with animated gradient backgrounds for buttons with light/dark outline.
> feat: Outline button hover effect

- packages/api/src/errors.js
- packages/api/test/pin.spec.js
Added contact details to error message for pinning unauthorized.
> feat: custom message for pin unauthorised

- packages/api/src/error-handler.js
- packages/api/src/errors.js
- packages/api/src/maintenance.js
> fix: handle maintenance error

- packages/website/pages/files.js
With this PR, I'd like to open up a discussion around how we display statuses and availability to users.
In this proposed solution we would slightly change how we communicate the status back to the user, hopefully, this approach would simplify and be less confusing to users.
The assumption here is that [https://web3.storage/files/](https://web3.storage/files/) should fulfill the following user outcomes when it communicating the status of an upload:
> As a user I want to know what's the status of my upload (rather than knowing what is the status of the cluster) so I reliably know if it was successful or not and my content is retrievable through the gateway, APIs, cli etc
Users don't really care about Web3.storage infra, if it's a IPFS cluster or something different to get hold of their …
> feat: remove availabilty and change status to be more general.

- packages/db/README.md
Adding some documentation for DB migrations workflow.
> chore: update migrations documentation

- packages/website/components/button/button.scss
- packages/website/components/navigation/navigation.js
- packages/website/components/navigation/navigation.scss
- packages/website/content/pages/general.json
- packages/website/next-env.d.ts
Removed heading in account dropdown menu + added active states to dropdown items. Nav items matching the current route are unable to be clicked and highlight in purple to indicate their active status.
This PR is currently waiting on a few items before it can be merged: 
- ~~link for 'Open an Issue' nav subitem: https://www.figma.com/file/AV3md9KWAZ6vOBLLCHnqoO?node-id=0:21476#154874457~~
- ~~possibly the addition of active states for current routes in the account nav submenu on mobile~~
> feat: Nav sublink active styles

- packages/website/components/card/card.js
- packages/website/components/card/card.scss
- packages/website/components/messagebanner/messagebanner.js
- packages/website/content/pages/index.json
- packages/website/pages/terms.scss
This PR contains:
- A few additions to the testimonial cards from [this ticket](https://app.asana.com/0/1200838779917290/1201861962218010/f): Links can now be added to descriptions either using markdown formatting or inline html elements. Also descriptions are now centered to avoid awkward spaces generated by longer descriptions stretching all card container heights.
- [Gradient underline on links in markdown content](https://app.asana.com/0/1198910434444850/1201861962218020) (terms page)
- a small bug fix which recalculates the message banner height _after_ a maintenance message is fetched as opposed to before
> feat: Interactions enhancements

- packages/docs/src/css/custom/nav.scss
- packages/website/.babelrc
- packages/website/components/account/filesManager/filesManager.tsx
- packages/website/components/account/storageManager/storageManager.tsx
- packages/website/components/contexts/uploadProgressContext.js
- packages/website/components/contexts/uploadsContext.js
- packages/website/components/contexts/userContext.js
- packages/website/components/general/appProviders.js
- packages/website/components/navigation/navigation.scss
- Adding ability to update used storage whenever deleting/uploading files
- Fixed issue with file name not coming through
> feat: priority QA updates for new frontend

- packages/website/components/account/filesManager/filesManager.tsx
- packages/website/components/tokens/tokenCreator/tokenCreator.js
- packages/website/components/tokens/tokensManager/tokensManager.js
- packages/website/modules/zero/components/pagination/pagination.js
- packages/website/modules/zero/hooks/useQueryParams.js
- Fixing query param reference in `useQueryParams`
- Reseting `page` query `order` parameter on change
- Fixing misc build errors that recently popped up
> fix: Pagination reset

- packages/client/src/lib.js
Sister PR of https://github.com/nftstorage/nft.storage/pull/1154
Closes #1060
> fix: client rate limit error message

- PEERS
Updates cluster peers 
cc @ribasushi
> chore: update cluster peers

- .env.tpl
- .github/workflows/cron-pins.yml
- packages/cron/README.md
- packages/cron/src/lib/utils.js
- packages/cron/test/pins.spec.js
This makes it behave the same as the other packages in the repo and therefore makes the env setup simpler.
> chore: make 'cron' package use the same ENV vars for its DB settings

- .github/workflows/cron-dagcargo-sizes.yml
> fix: cron dagcargo sizes secrets

- packages/db/index.js
> fix: upsert pins location ipfs_peer_id property name

- package-lock.json
- packages/docs/src/css/from-website/grid/gridlex-mixins.scss
- packages/website/components/account/filesManager/filesManager.tsx
- packages/website/components/tokens/tokensManager/tokenRowItem.js
- packages/website/components/tokens/tokensManager/tokensManager.js
- packages/website/components/tokens/tokensManager/tokensManager.scss
- packages/website/content/pages/app/tokens.json
- packages/website/pages/404.js
> fix: post launch fixes

- packages/website/components/account/storageManager/storageManager.tsx
- packages/website/components/contexts/userContext.js
> fix: user storage display on web

- packages/website/pages/about.js
This just modifies a comment in one of the site pages so we can get the release bot to pick up the changes from #1213 and see if that fixes our strange runtime issue.
> fix: trivial change to trigger release process

- packages/api/src/errors.js
- packages/api/src/upload.js
> fix: Return 400 on malformed form-data

- packages/website/content/pages/index.json
> fix: website copy filecoin storage capacity

- packages/website/components/account/filesManager/filesManager.js
- Minor type fix to revert optionality of `onFileUpload` for `filesManager.js`
> refactor: fixing incorrect type optionality for filesManager

- packages/api/src/car.js
- packages/api/src/constants.js
Per hector recommendation on updating to cluster v1
Closes https://github.com/web3-storage/web3.storage/issues/1238
> fix: api add to cluster always with local false

- packages/website/content/pages/general.json
Nav account dropdown changed to consolidate 'Dashboard' and 'Files' options to one item ('Manage Files') which navigates to the account page.
> feat: consolidate subnav account menu

- packages/docs/docs/how-tos/troubleshooting.md
Closes https://github.com/web3-storage/web3.storage/issues/1048
> feat: update troubleshooting docs

- packages/db/postgres/functions.sql
- packages/db/postgres/migrations/008-exclude-restricted-users.sql
- packages/db/test/pinning.spec.js
- packages/db/test/user-storage.spec.js
- packages/db/test/utils.js
> feat: ignore restricted users for storage emails

- packages/website/content/pages/app/account.json
fixes https://github.com/web3-storage/web3.storage/issues/1181
> fix: Change hover over description for Queuing in individual file rows

- packages/website/components/account/filesManager/filesManager.js
- packages/website/content/pages/app/account.json
fixes https://github.com/web3-storage/web3.storage/issues/1185
> fix: Default sort by should be newest to oldest

- packages/website/components/account/filesManager/filesManager.scss
The color of the file delete button in the app UI has been changed when in a disabled state.
> style: Delete file button in App UI modified

- packages/website/components/account/filesManager/filesManager.js
- packages/website/components/account/filesManager/filesManager.scss
- packages/website/content/pages/app/account.json
- packages/website/pages/account/index.js
Additional file upload button has been added to the files manager header in the app UI.
> feat: Additional file upload button

- package-lock.json
- packages/api/package.json
This gets us the fix to this: https://github.com/cloudflare/miniflare/issues/188 which is currently breaking all tests on the CI.
> fix: upgrade miniflare to ^2.4.0

- packages/website/components/account/fileUploader/fileUploader.js
- packages/website/modules/zero/components/dropzone/dropzone.js
- packages/website/modules/zero/components/dropzone/uploadProgress.js
Animated count upward between chunked points in file upload progress. This count is displayed in the file uploader component next to uploading files to visually indicate to the user that the file is indeed uploading and not hanging.
> feat: Upload progress feedback

- package-lock.json
- packages/website/components/account/storageManager/storageManager.js
- packages/website/components/account/storageManager/storageManager.scss
- packages/website/content/pages/app/account.json
The storage bar in the storage manager section of the app UI has been split into different colours corresponding to uploaded and pinned files. There is also an accompanying legend.
> feat: Pinned/uploaded storage bar feedback

- packages/cron/test/storage.spec.js
This PR update some tests that were calling external scripts and using stdout/stderr to assert actions. The tests are now using a mock, which also improves speed.
> chore: improve cron job testing for storage quota check

- packages/api/src/user.js
- packages/api/src/utils/tags.js
- packages/db/index.js
- packages/website/components/account/accountBlockedModal/accountBlockedModal.js
- packages/website/components/account/accountBlockedModal/accountBlockedModal.scss
- packages/website/components/account/ctaCard/CTACard.js
- packages/website/components/account/ctaCard/CTACard.scss
- packages/website/components/account/filesManager/filesManager.js
- packages/website/components/button/button.js
- packages/website/components/button/button.scss
- packages/website/components/contexts/userContext.js
- packages/website/components/tokens/tokenCreator/tokenCreator.js
- packages/website/content/pages/app/account.json
- packages/website/modules/zero/components/button/button.js
- packages/website/modules/zero/components/tooltip/tooltip.js
- packages/website/modules/zero/components/tooltip/tooltip.scss
- packages/website/pages/account/index.js
- packages/website/pages/account/index.scss
- packages/website/styles/global.scss
Mimicking recent changes to nft.storage, we're adding functionality here to display a modal when a user's account is restricted as well as disabled buttons and tooltips
Completes #1266
> feat: add user blocking functionality

- .github/workflows/cron-storage-limits.yaml
> chore: change the storage cron job to run in prod, and every 6 hours

- packages/website/pages/docs/how-tos/store.md
- packages/website/pages/docs/how-tos/troubleshooting.md
- packages/website/pages/docs/how-tos/work-with-car-files.md
- packages/website/pages/docs/reference/js-utilities.md
> fix: 404 API http reference links

- packages/website/README.md
- packages/website/public/schema.yml
> fix(http docs): incorrect endpoint in description

- package-lock.json
- packages/website/assets/illustrations/gradient-background.js
- packages/website/components/gradientbackground/gradientbackground.scss
add CF image optim to hero background 
ref: https://github.com/web3-storage/web3.storage/pull/1361
> fix: hero background

- packages/db/postgres/reset.sql
> fix: Adding user_tag_proposal schema to reset.sql for local dev

- packages/website/components/blog/categories.js
- packages/website/components/blog/tags.js
- packages/website/pages/blog/index.js
- packages/website/posts/2021-11-30-hello-world-nft-storage.mdx
- packages/website/posts/2021-12-14-storage-layer-maximalism.mdx
- packages/website/posts/2022-01-05-mikeal-modern-finance.mdx
- packages/website/posts/2022-01-20-decentralizing-nft-storage.mdx
- packages/website/posts/2022-01-31-q1-roadmap-and-beyond.mdx
- packages/website/posts/2022-02-08-what-am-buying.mdx
- packages/website/posts/2022-02-15-base-url-apis.mdx
- packages/website/posts/2022-02-21-use-web3-to-speed-up-web2.mdx
- packages/website/posts/2022-03-08-gateway-release.mdx
- packages/website/posts/2022-03-29-50M-uploads.mdx
- packages/website/posts/2022-04-01-gateway-ucan-release.mdx
- packages/website/posts/2022-04-04-missing-nfts.mdx
- packages/website/posts/2022-04-05-announcing-nftup.mdx
- packages/website/posts/2022-04-07-q2.mdx
- packages/website/posts/2022-04-29-gateways-and-gatekeepers.mdx
- packages/website/posts/2022-05-24-superhot-gateway-announcement.mdx
- Refactoring existing tags to `category` component
- Creating new `tags` component
- Refactoring blog index to support filtering by query params
- Integrating query params on tag/category/search actions
- Adding `category` to all example posts
> feat: Working filters for blog and category data

- .github/workflows/lint.yml
Bot to add comment on PRs with a human readable report of changes to package-lock.json
see: https://github.com/marketplace/actions/npm-lockfile-changes
**example**
> chore: add package-lock change report to PRs

- packages/website/pages/blog/index.js
- Adding ability to remove tags selected
> feat: Adding ability to remove tags

- packages/website/pages/blog/post/[slug].js
- packages/website/posts/2022-02-08-what-am-buying.mdx
- packages/website/posts/2022-02-15-base-url-apis.mdx
- packages/website/posts/2022-03-08-gateway-release.mdx
- Adding in logic to show related posts as follows:
```
- Add in most recent posts of same category first
- If related posts < 4 still, add in posts with matching tags (sorted by most tags which match first)
- If related posts < 4 still, add in posts at random from the remaining pool
```
> feat: Related posts logic

- packages/api/package.json
Thread from #nitro-team:
https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1655327312639659
API started failing locally with the following error:
@alanshaw suggested the fix and I'm applying it here as to not disrupt his flow.
> fix: add modules to miniflare

- packages/db/postgres/migrations/016-add-uploads-user-id-index.sql
- packages/db/postgres/migrations/018-add-uploads-user-id-index.sql
- packages/db/postgres/tables.sql
user_id on uploads should probably be indexed...
completes #61
> fix: naive take on adding an index

- packages/api/src/user.js
Ensures maintenance mode is read only when reading user.
> fix: ensure valid mode

- packages/cron/src/jobs/storage.js
Add some logging to the storage cron to facilitate performance auditing.
> fix: add logging to storage cron

- packages/api/src/user.js
> feat: update Storage Limit Request slack message to display 1TiB

- packages/client/src/lib.js
Just to trigger CI and see if DB staging has needed permissions and token updated.
CI failed https://github.com/web3-storage/web3.storage/runs/6972568141?check_suite_focus=true
> fix: client trigger ci

- packages/website/content/pages/general.json
> chore: update year in footer

- packages/website/components/navigation/navigation.scss
- packages/website/modules/docs-theme/index.scss
fixes #1385
This refactors the navigation hover to avoid undesired glitchy effects from the translateY transformation.
> feat: refactor navigation

- package-lock.json
- packages/cron/src/lib/utils.js
Fix [issue](https://github.com/web3-storage/web3.storage/runs/7075750428?check_suite_focus=true) with connection to cargo from cron.
> fix: pg connection string append ssl-true

- packages/cron/src/jobs/storage.js
- packages/cron/test/storage.spec.js
> fix: don't allow individual email sending failures to halt cron job

- packages/website/components/tokens/tokensManager/tokensManager.scss
- packages/website/content/pages/index.json
- packages/website/modules/docs-theme/swagger-ui.scss
- packages/website/modules/zero/components/slider/slider.js
- packages/website/pages/account/index.scss
- packages/website/pages/index.scss
- packages/website/styles/grid/gridlex-vars.scss
- packages/website/styles/variables.scss
> fix: aligns hero text to center of grid background

- packages/api/src/blog.js
- packages/api/src/index.js
- packages/website/lib/api.js
> fix: add blog subscription stub

- packages/cron/src/bin/delete-remote-pins.js
> fix: cron drop remote pins needs await

- packages/website/components/account/accountBlockedModal/accountBlockedModal.js
- packages/website/components/breadcrumbs/breadcrumbs.js
- packages/website/components/card/card.js
- packages/website/components/footer/footer.js
- packages/website/components/link/link.js
- packages/website/components/navigation/navigation.js
- packages/website/components/tokens/tokensManager/tokensManager.js
- packages/website/modules/docs-theme/sidebar/sidebar.js
- packages/website/pages/tokens/index.js
> feat: add a consolidated link component

- packages/website/components/footer/footer.js
- packages/website/modules/docs-theme/toc/toc.js
> fix: properly scroll to section when navigating to docs with a hash fragment

- packages/website/pages/docs/community/help-and-support.md
> feat: add a section explaining how to request more storage space

- packages/website/modules/docs-theme/toc/toc.js
> fix: show only a single selected nav item at a time

- packages/website/components/gradientbackground/gradientbackground.scss
- packages/website/components/pinningRequestModal/pinningRequestModal.js
- packages/website/components/storageLimitRequestModal/storageLimitRequestModal.js
- packages/website/styles/layouts/userRequestsModals.scss
- update textarea height to be more aligned with expected input
> fix: update user req modals to match site

- PEERS
We can update when the domain name changes.
> docs: add Elastic IPFS

- packages/website/.eslintrc.js
- packages/website/components/blog/tags/tags.js
- packages/website/modules/zero/hooks/useQueryParams.js
- packages/website/package.json
- packages/website/pages/blog/index.js
- packages/website/pages/blog/post/[slug].js
- Adding ability to not encode query params
- Making tags & categories sluggable
- Removing redundant eslint rules that were preventing commits due to conflicting packages
> feat: Sluggable blog tags/category & Removing redundant next/react linting

- package-lock.json
- packages/cron/package.json
- packages/cron/src/jobs/names.js
* Throttled requests to w3name to avoid rate limits
> fix: throttled names cron job requests

- packages/website/components/link/link.js
resolves https://github.com/web3-storage/web3.storage/issues/1678
> fix: footer 404s

- packages/db/index.js
* Now that admin.storage will set deleted_at there's no need to handle this in the applications.
> fix: Handling deleted_at on user requests from admin.storage (see nftstorage/admin.storage/issues/92)

- package-lock.json
- package.json
Per https://github.com/web3-storage/web3.storage/pull/1731#issuecomment-1213209673
> fix: upgrade wrangler

- .github/workflows/website.yml
e.g. https://w3s.link/ipfs/bafybeid7ichv3tih565ltnnuqo4a3phtj67tuann6mesdof4xezlgyxuwe
License: MIT
> chore: use w3s.link website preview

- packages/website/pages/docs/community/help-and-support.md
> fix: update verbiage on the help and support docs page

- .github/workflows/website.yml
- packages/api/package.json
- packages/api/src/user.js
- packages/website/tests/playwright/globalSetup.ts
What
* clean up website workflow
* clean up how api authenticates a magic token
Motivation
* At first this was experimental and I wasn't sure if it would lead to a patch for e2e-authn branch
> chore: clean up website workflow and magic token authentication

- .github/workflows/website.yml
- packages/api/package.json
- packages/api/src/magic.link.js
- packages/api/src/user.js
- packages/api/src/utils/env.js
- packages/website/scripts/envfile.ts
Note:
* non-main pr target
Motivation:
* experimenting with ways of resolving https://github.com/web3-storage/web3.storage/pull/1754#discussion_r951224046
> ci: website test-e2e does not write .env to disk

- packages/cron/src/jobs/names.js
> fix: add retry to fetch during IPNS record migration

- package-lock.json
- packages/client/package.json
- packages/client/src/name.js
- packages/client/test/name-e2e.spec.js
- packages/w3/package.json
> chore: add an e2e test for the w3name proxy module

- package-lock.json
- packages/client/package.json
- packages/w3/package.json
* Update w3name to support cjs
> fix: cjs support for w3name

- packages/website/components/account/filesManager/fileRowItem.js
- packages/website/components/account/filesManager/pinRequestRowItem.js
- packages/website/components/card/card.js
- packages/website/components/messagebanner/messagebanner.js
- packages/website/modules/zero/components/button/button.js
- packages/website/next.config.js
- packages/website/pages/account/index.js
> fix: prevent tabnabbing and clickjacking

- packages/website/content/pages/app/account.json
> fix: update storage column header verbiage

- packages/api/wrangler.toml
This PR specifies zone for wildcard route per https://github.com/web3-storage/web3.storage/issues/1842. This is a side effect of having [Cloudflare for SaaS](https://developers.cloudflare.com/cloudflare-for-saas/) enabled in our account
Closes #1842
> fix: wrangler publish wildcard route with specified zone id

- .github/workflows/website.yml
* Switch to organisation level Cloudflare tokens
> chore: update ci tokens

- .github/workflows/website.yml
- packages/api/README.md
- packages/api/scripts/cli.js
- packages/api/src/env.js
- packages/api/src/user.js
- packages/api/src/utils/billing-types.ts
- packages/api/src/utils/billing.js
- packages/api/src/utils/stripe.js
- packages/api/test/stripe.spec.js
- packages/db/index.js
- packages/db/postgres/migrations/023-add-user-customer-table.sql
- packages/db/postgres/tables.sql
- packages/db/test/hooks.js
Motivation:
* stay ahead of https://github.com/web3-storage/web3.storage/pull/1818#issuecomment-1239807728
* then I'll get [the issues/1779 PR](https://github.com/web3-storage/web3.storage/pull/1852) green so it can be a fast follow
> chore: incorporate post-review changes into issues/1779 branch

- packages/api/src/env.js
- packages/api/src/utils/logs.js
- packages/api/wrangler.toml
> chore: silence logging debug statements in test/dev

- packages/cron/src/jobs/metrics.js
Metrics job has been failing. One of the bottlenecks if the PIN count by status. As we move out of `ipfs-cluster`, this metrics is providing less value and we should just get rid of it.
> fix: cron not counting pin statuses

- .github/workflows/cron-pins.yml
- packages/cron/README.md
[1901](https://github.com/web3-storage/web3.storage/issues/1901)
> feat: split pins cron by environments

- packages/website/components/account/addPaymentMethodForm/addPaymentMethodForm.js
- packages/website/components/account/currentBillingPlanCard/currentBillingPlanCard.js
- packages/website/components/account/paymentMethodCard/paymentMethodCard.js
- packages/website/components/account/paymentTable.js/paymentTable.js
- packages/website/components/accountPlansModal/accountPlansModal.js
- packages/website/components/contexts/plansContext.js
- packages/website/lib/api.js
- packages/website/pages/account/index.scss
- packages/website/pages/account/payment.js
Motivation:
* fix bug discovered while testing on staging https://github.com/web3-storage/web3.storage/pull/1878
* bug prevented adding a payment method for the first time in both 'add payment form' in lower left of payment page as well as the form in the accountPlanModal
* I think this was introduced in [this commit](https://github.com/web3-storage/web3.storage/pull/1878/commits/8adff7beead71868cef8f7f2c9d813acab8c708d) after last PR review [approval](https://github.com/web3-storage/web3.storage/pull/1878#pullrequestreview-1112624754)
> fix: bugs saving credit card at /account/payment for the first time

- packages/website/content/pages/general.json
Motivation:
* conversation with @cmunns
> fix: rm menu item from global account menu

- packages/db/postgres/migrations/025-add-index-upload-by-type.sql
- packages/db/postgres/tables.sql
added indexes by type on upload's table
> feat: upload table indexes by type

- .github/workflows/api.yml
- packages/api/README.md
- packages/api/package.json
- packages/api/src/stripe.com/fixtures.json
Motivation:
* https://github.com/web3-storage/web3.storage/issues/1909
> feat: 1909 use stripe fixtures for website storage productprices

- packages/website/components/messagebanner/messagebanner.js
- packages/website/content/pages/general.json
https://www.notion.so/As-a-web3-storage-user-I-do-not-see-any-references-to-free-storage-on-the-website-or-the-looking-2d0ae9cb8e144ab2a9b4f1fd352a3577
> feat: remove nft.storage banner

- packages/website/components/account/paymentTable.js/paymentTable.js
- packages/website/components/accountPlansModal/accountPlansModal.js
- packages/website/components/accountPlansModal/accountPlansModal.scss
- packages/website/pages/account/payment.js
> feat: add TOS agree before confirm

- packages/website/components/link/link.js
- packages/website/components/navigation/navigation.js
- packages/website/content/pages/general.json
This PR adds a link to the new Web3 blog from the main navigation.
> feat: add blog link

- packages/website/content/pages/app/account.json
> fix: change verbiage on file manager legend

- packages/website/components/link/link.js
- packages/website/components/navigation/navigation.js
- packages/website/content/pages/general.json
This reverts commit 1289ac1921fe832b81d0dfa9e464b19ea8969481.
Per report https://twitter.com/Pranavbala2/status/1574665053193658370/photo/1
This is regression from latest release as the navigation options increased. I can only replicate signed in
> fix: revert "feat: add blog link (#1952)"

- packages/website/content/pages/general.json
Reverts web3-storage/web3.storage#1916
> feat: revert "fix: rm menu item from global account menu"

- packages/website/components/general/metadata.js
https://www.notion.so/Update-preview-summary-metadata-568ba710a5e94b27ae70099fed00b405
**This:**
With Web3.Storage you get all the benefits of decentralized storage and content addressing with the frictionless experience you expect in a modern storage solution. It’s fast, open and it’s free.
**Should be this:**
With web3.Storage you get all the benefits of decentralized storage and content addressing with the frictionless experience you expect in a modern storage solution. It’s fast and it's open.
> feat: update preview summary metadata

- packages/website/content/pages/general.json
- packages/website/content/terms-of-service.mdx
https://www.notion.so/update-Terms-of-Service-on-website-a8ea1c5eda1c43c7966a97334544c97a
> feat: update terms of service

- packages/website/content/pages/general.json
- packages/website/content/service-level-agreement.mdx
- packages/website/pages/sla.js
- packages/website/pages/sla.scss
- packages/website/styles/global.scss
https://www.notion.so/create-page-for-service-level-agreement-SLA-ba8320a690864adea373892c4ed4db65
> feat: create page for service level agreement

- packages/website/components/breadcrumbs/breadcrumbs.js
- packages/website/components/navigation/navigation.js
- packages/website/components/types.d.ts
- packages/website/content/pages/general.json
- packages/website/pages/404.js
- packages/website/pages/_app.js
- packages/website/pages/account/index.js
- packages/website/pages/account/payment.js
- packages/website/pages/callback/index.js
- packages/website/pages/contact.js
- packages/website/pages/faq.js
- packages/website/pages/login/index.js
- packages/website/pages/pricing.js
- packages/website/pages/products/w3link/index.js
- packages/website/pages/products/w3name/index.js
- packages/website/pages/products/web3storage/index.js
- packages/website/pages/sla.js
- packages/website/pages/terms.js
- packages/website/pages/tokens/index.js
* also includes a minor refactor of breadcrumbs so that they are more easily configured
Closes #1926
> fix: display proper breadcrumbs for product pages

- packages/website/components/account/filesManager/fileRowItem.js
- packages/website/components/account/filesManager/fileRowItem.scss
- packages/website/components/account/filesManager/uploadsTable.js
- packages/website/content/pages/app/account.json
> fix: add 'Complete' column to uploads table

- packages/website/content/pages/index.json
https://www.notion.so/Homepage-remove-squiggle-from-behind-text-9878cb8ec724460e86c9bdbe65d56635
Before:
After:
> fix: remove background squiggle

- packages/website/components/textblock/textblock.js
- packages/website/components/textblock/textblock.scss
- packages/website/content/pages/index.json
https://www.notion.so/Homepage-add-link-to-blog-post-723ba95d32c14ee0bcf91ddc1f7459b5
I looked into this a little yesterday.  It looks like it's going to involve changing blockbuilder two understand multiple ctas.  It's doable just more involved than I was looking for.  I'm going to come back to it tomorrow.
> feat: add link to blog post

- packages/api/scripts/generate-upload-data.js
> chore: improve error handling upload script

- packages/website/components/account/storageManager/storageManager.js
- packages/website/components/account/storageManager/storageManager.scss
- packages/website/components/accountPlansModal/accountPlansModal.js
> fix: missing prop for cc form in confirm modal

- packages/db/postgres/migrations/028-add-terms-of-service-table-agreement-type.sql
- packages/db/postgres/pg-rest-api-types.d.ts
- packages/db/postgres/reset.sql
- packages/db/postgres/tables.sql
This adds the table needed to support terms of service acceptance
> feat: add terms_of_service schema

- packages/website/pages/docs/community/help-and-support.md
go ahead and merge @yusefnapora after you've approved!
> fix: no more request storage in docs

- packages/api/src/auth.js
- packages/api/src/utils/logs.js
Motivation:
* https://github.com/web3-storage/web3.storage/issues/2040
> fix: issue with logging user being set to different value than underlying user.id bigint::text

- .github/CODEOWNERS
Motivation:
* https://www.notion.so/1c6ce217e4be45a28a59a6dfe5faac59?v=74ff5c5797964a05acec8c74580b172b
> ci: add .github/CODEOWNERS with rule where repo owned by @web3-storage/dag-house

- packages/website/components/w3link_form/w3link_form.scss
Simple fix to resolve style regression. See attached issue for more context
> fix: incorrect class use

- packages/api/src/pins.js
- packages/api/src/utils/psa.js
- packages/api/test/pin.spec.js
> fix: allow update PSA pin requests with same CID

- packages/website/components/account/storageManager/storageManager.js
- packages/website/components/account/storageManager/storageManager.scss
- packages/website/content/pages/app/account.json
> feat: add tooltip to dashboard storage totals

- packages/website/components/customStorageForm/customStorageForm.scss
> fix: styles missing from custom storage form

- packages/api/src/errors.js
- packages/api/src/utils/psa.js
- packages/api/test/pin.spec.js
> fix: reject not supported codecs

- packages/db/index.d.ts
- packages/db/index.js
- packages/db/test/user.spec.js
> fix: db query for blocked token when not blocked should not error

- packages/website/components/account/storageManager/storageManager.js
- packages/website/components/accountPlansModal/accountPlansModal.js
- packages/website/components/contexts/plansContext.js
- packages/website/hooks/use-payment.js
- packages/website/lib/api.js
- packages/website/pages/account/payment.js
Closes #2218 
Users without a subscription will no longer be treated as early adopters, but as Free tier users.
> fix: display those with no subscription as Free Tier users

- packages/website/components/accordionblock/accordionblock.js
- packages/website/components/accordionsingle/accordionsingle.js
- packages/website/components/navigation/navigation.js
- packages/website/modules/zero/components/accordion/accordionSection.js
* Also fixes an issue with nested anchor tags
Fixes #2223
> fix: fix app failure when clicking 'Account +' on mobile

- packages/api/src/pins.js
let undialable nodes connect to us when using the pinning service api to pin a cid.
The delegate multiaddrs are ephemeral, so no effort is made here to store the info in the db.
Kubo will only use delegates when provided in the initial pin add response anyway. Providing them in a subsequent pin status response does not trigger kubo to connect to them.
uses `delegates` that will be set on metadata when https://github.com/web3-storage/pickup/pull/134 lands
License: MIT
> feat: provide delegates on pin add response

- package-lock.json
- packages/website/components/accordionblock/accordionblock.js
- packages/website/content/pages/faq.json
- packages/website/package.json
- packages/website/pages/faq.js
This PR updates the FAQ page to fetch content from the Netlify blog and content site.
> feat: load faq content from Netlify

- .github/workflows/cron-pins.yml
> fix: pickup URL

- packages/website/pages/docs/how-tos/w3name.md
> fix: w3name docs

- packages/website/pages/docs/how-tos/store.md
> fix: curl http header arg name

- .github/workflows/cron-test-pinning.yml
- .github/workflows/cron-test-upload.yml
moving to grafana hosted pushgateway
License: MIT
> chore: update pushgateway
